const CASE_KEY='pa_case_manager_core';
const CASES={
  gp:{name:'GP / Primary Care',tags:/\bgp\b|doctor|practice|banbridge group|dr cullen|dr dillon|dr mcniff/i,domain:'Healthcare'},
  rheum:{name:'Rheumatology / hEDS-HSD',tags:/rheumatology|rheumatologist|heds|hsd|hypermobility|joint|beighton/i,domain:'Healthcare'},
  thyroid:{name:'Thyroid Nodule',tags:/thyroid|nodule|ultrasound|endocrine/i,domain:'Healthcare'},
  oral:{name:'Oral Medicine / Dentistry',tags:/dentist|dental|oral|burning mouth|tmj|jaw|gum|tooth|catherine|claire/i,domain:'Healthcare'},
  social:{name:'Social Care / Mary-Sue / Cherrytrees',tags:/social care|mary-sue|mary sue|cherrytrees|physical disability team|care plan|assessment/i,domain:'Social Care'},
  pip:{name:'PIP',tags:/\bpip\b|personal independence payment|assessment|mandatory reconsideration|tribunal/i,domain:'Benefits'},
  uc:{name:'Universal Credit / LCWRA / Appointee',tags:/universal credit|\buc\b|lcwra|appointee|work coach|mollie/i,domain:'Benefits'},
  bank:{name:'Banking / AIB / LCS',tags:/aib|bank|payment|direct debit|standing order|chargeback|refund|lcs|1st locate|debt|fraud|scam/i,domain:'Finance'},
  housing:{name:'Housing / Repairs / Lotus',tags:/housing|repair|lotus|clixifix|leak|water ingress|alarm|boiler|plumber|electric|lights/i,domain:'Housing'},
  utilities:{name:'Utilities / Priority Services',tags:/power ni|nie networks|electricity|gas|utility|priority service|care register/i,domain:'Utilities'},
  access:{name:'Accessibility / Reasonable Adjustments',tags:/reasonable adjustment|accessibility|easy read|written summary|no phone|telephone|aac|communication|autism|autistic|visual aids|body chart/i,domain:'Accessibility'}
};
function paAutoRouter(){
  shell('Case Manager Intake','<div class="card out"><b>Rule:</b> everything enters Case Manager first. PA links it to active cases, evidence, open loops, recovery and drafts before showing you one next step.</div><textarea id="intakeText" rows="8" placeholder="Paste anything here: email, letter, appointment, screenshot text, form text, message, file name."></textarea><input id="intakeFile" type="file" accept="image/*,.pdf,.txt,.doc,.docx" onchange="paFilePicked()">'+grid([
    ['🪄 Process Clipboard','paProcessClipboard()','primary'],['✅ Process Intake','paProcessIntake()','primary'],['🧠 Case Manager','paCaseManager()'],['📋 Last Result','paShowLast()']
  ])+'<div id="out" class="card out"></div>')
}
async function paProcessClipboard(){let text='';try{text=await navigator.clipboard.readText()}catch(e){set('out','Clipboard blocked. Copy text first, then try again.');return}if(!text||!text.trim()){set('out','Clipboard is empty. Copy a message first.');return}let e=document.getElementById('intakeText');if(e)e.value=text.trim();paRouteText(text.trim(),{source:'clipboard'})}
function paProcessIntake(){const text=v('intakeText');const file=document.getElementById('intakeFile')?.files?.[0];if(!text&&!file){set('out','Nothing to process. Paste text or choose a file.');return}paRouteText(text||('[File uploaded: '+file.name+']'),{source:file?'file/manual':'manual',file:file?{name:file.name,type:file.type,size:file.size}:null})}
function paFilePicked(){const f=document.getElementById('intakeFile')?.files?.[0];if(!f)return;set('out','File selected: '+f.name+'\n\nOn iPhone: use Live Text to copy words from the image, paste them above, then press Process Intake. If you upload the image directly in ChatGPT, I can read it and use connectors/history there.')}
function paRouteText(text,meta={}){
  const ctx=paAnalyse(text,meta),tasks=paCreateTasks(ctx),mum=paMumSummary(ctx,tasks),reply=paDraft(ctx.route,ctx),caseState=paUpdateCases(ctx,tasks,text),result=paRenderResult(ctx,tasks,mum,reply,caseState);
  const payload={timestamp:new Date().toISOString(),domain:ctx.route,source:'PA Case Manager Intake',contact:ctx.contact,cases:ctx.caseNames,summary:ctx.bottomLine,priority:ctx.priority,action_needed:ctx.action,deadline:ctx.deadline,appointment:ctx.appointment,tasks,mum_summary:mum,draft_reply:reply,result,original:text,evidence_flag:ctx.route!=='General'};
  localStorage.pa_last_task=JSON.stringify(payload);paLogToMira(payload);add(MK.line,{a:'PA Case Manager Intake: '+ctx.route,b:ctx.bottomLine+'\nCases: '+ctx.caseNames.join(', ')+'\n'+text});add(MK.doc,{a:'PA Case Manager result: '+ctx.route,b:result});if(ctx.evidence)add(MK.ev,{a:'Evidence captured: '+ctx.route,type:ctx.route,b:ctx.bottomLine});tasks.forEach(t=>add(t.queue,{a:t.title,org:ctx.route,status:t.status,b:t.detail}));if(ctx.openLoop)add(MK.loop,{a:'Open loop: '+ctx.contact,org:ctx.contact,status:'Waiting / watch',b:ctx.bottomLine});
  document.getElementById('out').innerHTML='<pre style="white-space:pre-wrap;font-family:inherit">'+escapeHtml(result)+'</pre>'+grid([['👩 Copy Mum Chinese','paTellMum()','primary'],['📋 Copy reply','paCopyReply()'],['📅 Calendar draft','paCalendarDraft()'],['🧠 Case Manager','paCaseManager()'],['🧾 Show tasks','paShowTasks()'],['↩ Intake','paAutoRouter()']]);
}
function paAnalyse(text,meta={}){
  const low=(text||'').toLowerCase();let route='General';
  if(/nhs|hscni|trust|gp|doctor|hospital|clinic|appointment|rheumatology|dentist|pharmacy|prescription|blood test|scan|referral/.test(low)) route='Healthcare';
  else if(/pip|dwp|universal credit|\buc\b|lcwra|benefit|dfc|mandatory reconsideration|tribunal|assessment/.test(low)) route='Benefits';
  else if(/bank|payment|direct debit|refund|chargeback|invoice|debt|standing order|aib|lcs|scam|fraud/.test(low)) route='Finance';
  else if(/repair|housing|leak|alarm|electric|builder|lotus|plumber|clixifix|boiler|water ingress/.test(low)) route='Housing';
  else if(/college|university|course|student|open university|study|assignment/.test(low)) route='Education';
  else if(/autism|autistic|reasonable adjustment|sensory|aac|disability|accessibility|easy read/.test(low)) route='Accessibility';
  const caseKeys=Object.keys(CASES).filter(k=>CASES[k].tags.test(text));if(!caseKeys.length&&route!=='General')caseKeys.push(route.toLowerCase());
  const deadline=paDate(text)||'No clear date found',appointment=/appointment|attend|clinic|hospital|dentist|rheumatology|gp|blood test|scan|review/i.test(text),action=/reply|required|complete|return|confirm|book|attend|deadline|before|by |call|contact|provide|send|submit|form/i.test(text)||appointment,risk=/urgent|final|overdue|missed|debt|fraud|scam|cancel|suspend|appointment|deadline|termination|failure to/i.test(text),phone=/phone|call|telephone/i.test(text),evidence=/nhs|hscni|trust|gp|hospital|pip|dwp|uc|universal credit|bank|aib|housing|repair|social care|assessment|autism|reasonable adjustment/i.test(text),openLoop=/will contact|waiting|referral|follow up|respond|reply|investigation|review|arrange|book|confirm/i.test(text),rec=Number(localStorage.mn_recovery_until||0)>Date.now();
  const contact=paContact(route,low),priority=risk?'RED - check, do not ignore':(action?'AMBER - one review step':'GREEN - file / wait'),caseNames=caseKeys.map(k=>CASES[k]?.name||k);
  const bottomLine='This belongs to '+(caseNames.length?caseNames.join(' + '):route')+'. '+(appointment?'Appointment-related. ':action?'May need one action. ':'No immediate action clear. ')+(phone?'Phone/call mentioned: use written-only wording. ':'')+(rec?'Recovery mode active: reduce demands.':'');
  return {route,caseKeys,caseNames,deadline,appointment,action,risk,phone,evidence,openLoop,contact,priority,bottomLine,text,meta,recovery:rec};
}
function paDate(text){const patterns=[/\b\d{1,2}[\/\-. ]\d{1,2}[\/\-. ]\d{2,4}\b/,/\b\d{1,2}\s+(January|February|March|April|May|June|July|August|September|October|November|December)\s+\d{4}\b/i,/\b(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)\s+\d{1,2}\s+(January|February|March|April|May|June|July|August|September|October|November|December)\b/i];for(const p of patterns){const m=text.match(p);if(m)return m[0]}return ''}
function paCreateTasks(ctx){const tasks=[];if(ctx.evidence)tasks.push({title:'Evidence linked to case',queue:K.wait,status:'Done / saved',detail:'Saved to Mira and linked to: '+(ctx.caseNames.join(', ')||ctx.route)});if(ctx.appointment){tasks.push({title:'Prepare appointment pack',queue:K.ready,status:'Ready / one step',detail:'Mellow AAC, questions, written/no-phone adjustments, Easy Read, written summary, body chart/visual aids if useful.'});tasks.push({title:'48h recovery block',queue:K.hidden,status:'Recovery shield',detail:'Hide banking, benefits forms, difficult emails and complex admin after appointment.'});tasks.push({title:'Post-appointment follow-up',queue:K.wait,status:'Waiting / after appointment',detail:'Check written summary, referrals, results, owner and timescale.'})}else if(ctx.action){tasks.push({title:'Review '+ctx.route+' item',queue:K.ready,status:'Ready / one small step',detail:'Use bottom line and draft. Do not re-read everything.'})}else tasks.push({title:'Filed to Case Manager',queue:K.wait,status:'Waiting / no action now',detail:'No clear action. Kept as case evidence.'});if(ctx.deadline!=='No clear date found')tasks.push({title:'Date found: '+ctx.deadline,queue:K.ready,status:'Calendar/check needed',detail:'Confirm if this is appointment, deadline or information date.'});if(ctx.phone)tasks.push({title:'Block phone demand',queue:K.ready,status:'Accessibility wording needed',detail:'Use written-only / no phone script.'});if(ctx.openLoop)tasks.push({title:'Open loop watch',queue:K.wait,status:'Waiting / chase if overdue',detail:'Someone may need to reply, arrange, confirm or follow up.'});return tasks}
function paUpdateCases(ctx,tasks,text){let cm={};try{cm=JSON.parse(localStorage[CASE_KEY]||'{}')}catch(e){};const keys=ctx.caseKeys.length?ctx.caseKeys:['general'];keys.forEach(k=>{let def=CASES[k]||{name:ctx.route,domain:ctx.route};let c=cm[k]||{name:def.name,domain:def.domain,status:'Active',phase:'Intake',owner:'Unknown',waiting_for:'Not set',evidence:[],deadlines:[],risks:[],next_action:'None',updated:null};c.updated=new Date().toISOString();c.phase=ctx.appointment?'Appointment / preparation':ctx.openLoop?'Waiting / open loop':ctx.action?'Action review':'Evidence / waiting';c.waiting_for=ctx.openLoop?ctx.contact:(ctx.action?'Menglu review only if needed':'No action now');c.owner=ctx.contact||c.owner;c.next_action=paNextStep(ctx);if(ctx.deadline!=='No clear date found')c.deadlines.unshift(ctx.deadline);if(ctx.risk)c.risks.unshift(ctx.priority);c.evidence.unshift({date:new Date().toISOString(),summary:ctx.bottomLine,text:text.slice(0,900)});c.tasks=tasks.map(t=>t.title+' — '+t.status);cm[k]=c});localStorage[CASE_KEY]=JSON.stringify(cm);return cm}
function paRenderResult(ctx,tasks,mum,reply,caseState){return 'CASE MANAGER INTAKE\n\nACTIVE CASE\n'+(ctx.caseNames.join('\n')||ctx.route)+'\n\nBOTTOM LINE\n'+ctx.bottomLine+'\n\nIMPORTANCE\n'+ctx.priority+'\n\nDATE / DEADLINE FOUND\n'+ctx.deadline+'\n\nTODAY?\n'+(ctx.risk?'YES - check calmly or ask support.':ctx.action?'POSSIBLY - one review step only.':'NO clear action today.')+'\n\nONE SAFEST NEXT STEP\n'+paNextStep(ctx)+'\n\nTASKS CREATED\n'+tasks.map(t=>'✓ '+t.title+' — '+t.status).join('\n')+'\n\nMUM CHINESE\n'+mum+'\n\nDRAFT REPLY IF NEEDED\n'+reply}
function paNextStep(ctx){if(ctx.appointment)return 'Confirm date/time/location, prepare Mellow AAC, and protect 48h recovery afterwards.';if(ctx.phone)return 'Do not phone. Use written-only reply or ask for written clarification.';if(ctx.risk)return 'Do not ignore. Review with support or use draft asking for written confirmation.';if(ctx.action)return 'Use prepared reply or keep as one ready task. Stop after one step.';return 'No action now. Save to Case Manager and wait.'}
function paMumSummary(ctx,tasks){return '妈妈，简单说：\n\n这条信息属于：'+(ctx.caseNames.join(' / ')||ctx.route)+'。\n\n重点：'+ctx.bottomLine+'\n\n日期/截止时间：'+ctx.deadline+'\n\n下一步：'+paNextStep(ctx)+'\n\nPA 已经保存到 Case Manager，并自动生成任务。请不要让我打电话；重要事情尽量用文字处理。'}
function paCaseManager(){let cm={};try{cm=JSON.parse(localStorage[CASE_KEY]||'{}')}catch(e){};let rows=Object.values(cm).sort((a,b)=>(b.updated||'').localeCompare(a.updated||''));shell('Case Manager Core','<div class="card out">Every input is linked to active cases. This prevents isolated emails and reduces repeated explaining.</div>'+(rows.length?rows.map(c=>'<div class="card small"><b>'+escapeHtml(c.name)+'</b><br>Status: '+escapeHtml(c.status||'Active')+'<br>Phase: '+escapeHtml(c.phase||'')+'<br>Waiting for: '+escapeHtml(c.waiting_for||'')+'<br>Next: '+escapeHtml(c.next_action||'')+'<br>Evidence items: '+(c.evidence?.length||0)+'<br>Updated: '+escapeHtml(c.updated||'')+'</div>').join(''):'<div class="card out">No case records yet. Use Intake first.</div>')+grid([['🪄 New intake','paAutoRouter()','primary'],['📋 Last result','paShowLast()'],['🚦 Pacing','demandPacing()']]))}
function paContact(route,low){if(route==='Finance')return low.includes('aib')?'AIB / bank support':'Finance contact';if(route==='Healthcare')return low.includes('trust')||low.includes('hscni')?'Southern Trust / healthcare team':low.includes('gp')?'GP / healthcare team':'Healthcare contact';if(route==='Benefits')return low.includes('universal credit')||/\buc\b/.test(low)?'Universal Credit':'Benefits contact';if(route==='Housing')return low.includes('lotus')?'Lotus / housing repair contact':'Housing / repair contact';if(route==='Accessibility')return 'Accessibility / reasonable adjustments';return 'Unknown / not matched'}
function paLogToMira(payload){let a=[];try{a=JSON.parse(localStorage.mira_next_timeline||'[]')}catch(e){}a.unshift(payload);localStorage.mira_next_timeline=JSON.stringify(a);localStorage.mira_next_active_session=JSON.stringify(payload)}
function paCopyMiraPayload(){let x=JSON.parse(localStorage.pa_last_task||'{}');copyText(JSON.stringify(x,null,2));set('out','Mira payload copied. Also saved locally under mira_next_timeline and active session.')}
function paCopyReply(){let x=JSON.parse(localStorage.pa_last_task||'{}');copyText(x.draft_reply||'');set('out','Draft reply copied. Review before sending. PA does not auto-send.')}
function paTellMum(){let x=JSON.parse(localStorage.pa_last_task||'{}');copyText(x.mum_summary||'没有可复制的妈妈总结。');set('out',x.mum_summary||'没有可复制的妈妈总结。')}
function paCalendarDraft(){let x=JSON.parse(localStorage.pa_last_task||'{}');let t='Calendar draft\n\nTitle: '+(x.domain||'Item')+' - '+(x.contact||'')+'\nDate found: '+(x.deadline||'Not found')+'\nNotes:\n- Bring/use Mellow AAC if needed.\n- Request written summary / Easy Read.\n- No phone; written contact preferred.\n- Protect 48h recovery afterwards.\n\nIf date/time is definite, ask ChatGPT to add this to Google Calendar.';copyText(t);set('out',t)}
function paShowTasks(){let x=JSON.parse(localStorage.pa_last_task||'{}');let t='TASKS CREATED\n\n'+((x.tasks||[]).map(a=>'• '+a.title+'\n  '+a.status+'\n  '+a.detail).join('\n\n')||'No tasks found.');set('out',t)}
function paDraft(route,ctx={}){const noPhone='Please communicate with me in writing. Telephone contact is not accessible or safe for me.';const context='Please confirm what this means, what action is required, who is responsible, and the deadline or timescale.';if(route==='Finance')return 'Dear Team,\n\nPlease confirm the issue, amount, date, responsible team and next step in writing. '+noPhone+'\n\nKind regards,\nMenglu Liu';if(route==='Healthcare')return 'Dear Team,\n\nThank you for your message. Because of my disability-related communication, processing and fatigue difficulties, '+context+' Please also provide an Easy Read or simple written summary where possible. '+noPhone+'\n\nKind regards,\nMenglu Liu';if(route==='Benefits')return 'Dear Team,\n\nThank you for your message. Because of my disability-related communication, processing and executive functioning difficulties, '+context+' Please confirm any reasonable adjustments available. '+noPhone+'\n\nKind regards,\nMenglu Liu';return 'Dear Team,\n\nThank you for your message. Because of my disability-related communication and processing difficulties, '+context+'\n\nKind regards,\nMenglu Liu'}
function paResume(){let x=null;try{x=JSON.parse(localStorage.pa_last_task||'null')}catch(e){}if(!x){paAutoRouter();return}shell('Continue where I stopped','<div class="card out">Last task:\n'+(x.domain||'Unknown')+'\n'+(x.timestamp||'')+'</div>'+grid([['Resume result','paShowLast()','primary'],['Copy Mum Chinese','paTellMum()'],['Copy reply','paCopyReply()'],['Case Manager','paCaseManager()'],['Clear and start again','paClearLast()']])+'<div id="out" class="card out"></div>')}
function paShowLast(){let x=null;try{x=JSON.parse(localStorage.pa_last_task||'null')}catch(e){}if(!x){paAutoRouter();return}shell('Last Case Manager Result','<pre class="card out" style="white-space:pre-wrap;font-family:inherit">'+escapeHtml(x.result||JSON.stringify(x,null,2))+'</pre>'+grid([['Copy Mum Chinese','paTellMum()','primary'],['Copy reply','paCopyReply()'],['Calendar draft','paCalendarDraft()'],['Show tasks','paShowTasks()'],['Case Manager','paCaseManager()'],['Back to Intake','paAutoRouter()']])+'<div id="out" class="card out"></div>')}
function paClearLast(){delete localStorage.pa_last_task;delete localStorage.mira_next_active_session;paAutoRouter()}
function escapeHtml(s){return String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
