const app=document.getElementById('app');
const K={inbox:'pa_inbox',ready:'pa_ready',wait:'pa_wait',hidden:'pa_hidden',log:'pa_log',finance:'pa_finance',boundary:'pa_boundary'};
const MK={line:'mn_line',doc:'mn_doc2',loop:'mn_loop',ev:'mn_ev'};
function arr(k){try{return JSON.parse(localStorage[k]||'[]')}catch(e){return[]}}
function add(k,o){let a=arr(k);o.date=new Date().toLocaleString('en-GB');a.unshift(o);localStorage[k]=JSON.stringify(a)}
function v(id){return document.getElementById(id)?.value.trim()||''}
function set(id,t){let e=document.getElementById(id);if(e)e.textContent=t}
function shell(t,b){app.innerHTML='<div class="card soft"><b>'+t+'</b><p class="small">Cognitive firewall: PA filters demands before they reach you.</p></div>'+b}
function grid(a){return '<div class="grid">'+a.map(x=>'<button class="'+(x[2]||'')+'" onclick="'+x[1]+'">'+x[0]+'</button>').join('')+'</div>'}
async function pasteTo(id){let e=document.getElementById(id);try{e.value=await navigator.clipboard.readText();e.focus()}catch(err){e.focus();set('out','Paste manually.')}}
function copyText(t){navigator.clipboard.writeText(t).catch(()=>{})}
function typeOf(s){s=(s||'').toLowerCase();if(/nhs|hospital|gp|clinic|appointment|doctor|rheumatology|dentist/.test(s))return 'healthcare';if(/pip|universal credit|uc|dwp|benefit|lcwra|dfc/.test(s))return 'benefits';if(/bank|payment|direct debit|refund|chargeback|scam|aib|lcs|debt/.test(s))return 'finance';if(/repair|housing|lotus|leak|alarm|plumber|electric/.test(s))return 'housing';if(/mum|mother|family|wechat|妈妈/.test(s))return 'family';return 'general'}
function needAction(s){return /reply|required|deadline|by |before|within|appointment|book|confirm|urgent|call|phone/i.test(s||'')}
function home(){let rec=Number(localStorage.mn_recovery_until||0)>Date.now();shell('Menglu PA Shield','<div class="card out">'+(rec?'Recovery mode is active. PA should hide complex demands.':'PA is ready. Paste one thing and PA will shield you from the full demand.')+'\n\nReady: '+arr(K.ready).length+' | Waiting: '+arr(K.wait).length+' | Hidden: '+arr(K.hidden).length+'</div>'+grid([['🛡 Shield Incoming','shieldIncoming()','primary'],['🚪 Outside Planner','outsideMode()','primary'],['🎚 Tone Dial Reply','toneDial()'],['📄 Paperwork Card','paperworkCard()'],['🚦 Demand Pacing','demandPacing()'],['💷 Finance Guard','financeGuard()']]))}
function outsideMode(){shell('Outside Planner','<div class="card out">For necessary outings only. Keep the plan small and protect recovery afterwards.</div>'+grid([['Leaving checklist','leavingChecklist()','primary'],['Shop card','shopCard()'],['Travel note','travelNote()'],['Return home check','safeReturn()','primary'],['Start recovery','startRecovery()','danger'],['Open Mellow','location.href="../"']])+'<div id="out" class="card out"></div>')}
function leavingChecklist(){let t='Before going outside:\n\n□ Phone charged\n□ Water ready\n□ Needed items ready\n□ Return plan confirmed\n□ Mellow AAC available\n□ Do not add extra tasks\n□ Recovery time protected afterwards\n\nRule: one outing should not become several tasks.';set('out',t);copyText(t)}
function shopCard(){let t='I have communication and processing difficulties today. Please use short clear sentences. I may need to point, use contactless payment, avoid long waiting, and finish quickly. Thank you.';set('out',t);copyText(t)}
function travelNote(){let t='Accessibility note: I may need seating, reduced waiting, clear written instructions, and support from a carer. Please avoid fast verbal instructions where possible.';set('out',t);copyText(t)}
function safeReturn(){let t='Return home check:\n\n□ Sit or lie down\n□ Drink water\n□ Food if needed\n□ No banking\n□ No forms\n□ No difficult emails\n□ Record only if something important happened\n\nIf the outing was difficult, start recovery mode.';set('out',t);copyText(t);add(MK.line,{a:'Returned from outing',b:'Safe return check opened in PA.'})}
function shieldIncoming(){shell('Communication Shield','<div class="card small">Paste an email, text, letter, or message. PA removes noise and shows only meaning, action, risk, and safest next step.</div><textarea id="msg" rows="8" placeholder="Paste stressful message here"></textarea>'+grid([['Paste','pasteTo("msg")'],['Decode + shield','decodeMessage()','primary']])+'<div id="out" class="card out"></div>')}
function decodeMessage(){let x=v('msg'),t=typeOf(x),act=needAction(x),risk=/urgent|final|debt|overdue|missed|deadline|fraud|scam|appointment/i.test(x);let safeReply='Dear Team,\n\nThank you for your message. Because of my disability-related communication and processing difficulties, please continue in writing and confirm:\n\n1. what this means,\n2. what action is required from me,\n3. who is responsible, and\n4. the deadline or timescale.\n\nKind regards,\nMenglu Liu';let out='COMMUNICATION SHIELD\n\nType: '+t+'\nMeaning: This appears to be a '+t+' message.\nAction from Menglu: '+(act?'Possibly yes - review only one next step.':'No immediate action found. Put in Waiting.')+'\nRisk level: '+(risk?'Check calmly / do not ignore':'Low or unclear')+'\n\nSafest next step:\n'+(act?'Ask for written clarification or prepare one reply.':'File it and wait. Do not spend energy now.')+'\n\nDraft safe reply:\n'+safeReply;set('out',out);add(K.inbox,{type:t,text:x,result:out});add(act?K.ready:K.wait,{a:'Shielded '+t+' message',org:t,status:act?'Ready / review one step':'Waiting / no action now',b:'Decoded by PA.'});add(MK.line,{a:'PA shielded '+t+' message',b:x});add(MK.doc,{a:'PA shield output: '+t,b:out});if(risk)add(MK.ev,{a:'High-load incoming message',type:t,b:'PA used to reduce cognitive and communication load.'})}
function toneDial(){shell('Tone Dial Reply','<div class="card small">Write rough thoughts. Choose tone. PA turns it into a usable message.</div><textarea id="rough" rows="6" placeholder="Example: I cannot go. Too tired. Need written reply."></textarea><div class="grid"><button onclick="makeTone(\'professional\')">Professional</button><button onclick="makeTone(\'friendly\')">Friendly boundary</button><button onclick="makeTone(\'direct\')">Direct</button><button onclick="makeTone(\'extension\')">Request extension</button></div><div id="out" class="card out"></div>')}
function makeTone(mode){let r=v('rough')||'I cannot manage this at the moment.';let m={professional:'Dear Team,\n\nThank you for your message. I am not able to manage this immediately due to disability-related fatigue, processing and communication difficulties. Please confirm the essential next step in writing and allow additional time where possible.\n\nKind regards,\nMenglu Liu',friendly:'Thank you for understanding. I am not able to manage this right now because my energy and processing capacity are limited. I will need to keep things simple and in writing.',direct:'I cannot manage this right now. Please put the next step in writing and do not phone me.',extension:'Dear Team,\n\nBecause of disability-related fatigue, processing and communication difficulties, I need additional time to respond. Please confirm whether an extension is possible and provide the next step in writing.\n\nKind regards,\nMenglu Liu'}[mode];let out='Tone: '+mode+'\n\nRaw meaning:\n'+r+'\n\nDraft:\n'+m;set('out',out);add(K.boundary,{mode,raw:r,draft:m});add(MK.doc,{a:'Tone Dial draft: '+mode,b:out})}
function paperworkCard(){shell('Paperwork Card','<div class="card small">Paste text from a letter/form. PA creates a clean card: due date, action, contact, risk.</div><textarea id="paper" rows="8" placeholder="Paste letter/form text"></textarea>'+grid([['Paste','pasteTo("paper")'],['Make card','makePaperCard()','primary']])+'<div id="out" class="card out"></div>')}
function makePaperCard(){let x=v('paper'),t=typeOf(x),date=(x.match(/\b\d{1,2}[\/\-\. ]\d{1,2}[\/\-\. ]\d{2,4}\b/)||['Not found'])[0],phone=/phone|call|telephone/i.test(x);let out='PAPERWORK CARD\n\nType: '+t+'\nDue date found: '+date+'\nAction required: '+(needAction(x)?'Possible action - review carefully':'No clear action found')+'\nContact method risk: '+(phone?'Phone mentioned - request written contact instead':'No phone demand found')+'\n\nNext step:\nDo not read full fine print again. Use this card and ask for written clarification if needed.';set('out',out);add(K.ready,{a:'Paperwork card: '+t,org:t,status:'Card created',b:'Due date: '+date});add(MK.doc,{a:'Paperwork card: '+t,b:out+'\n\nOriginal:\n'+x})}
function financeGuard(){shell('Finance Guard','<div class="card out">Use this for money anxiety, bills, suspicious payments or spending pressure.\n\nRule: do not make financial decisions during burnout, panic, PEM, sensory overload, or after appointments.</div>'+grid([['Check finance demand','financeDemand()','primary'],['48h cooling text','coolingText()'],['Bank written-only script','bankScript()'],['Open Mira Money','location.href="../mira-next/"']])+'<div id="out" class="card out"></div>')}
function financeDemand(){set('out','Finance Shield questions:\n\n1. Is this a bill, refund, debt, scam, subscription or Direct Debit?\n2. Is money leaving now?\n3. Is there a deadline?\n4. Is written proof available?\n5. Should this wait for support?\n\nSafe default: pause, do not phone, ask for written confirmation, involve support if uncertain.');add(K.finance,{a:'Finance shield used',status:'Safety pause',b:'No immediate decision recommended.'})}
function coolingText(){let t='I need time to review this safely. Because of disability-related fatigue, processing difficulties and vulnerability to overwhelm, I will not make an immediate financial decision. Please provide written information and allow time for support/review.';set('out',t);copyText(t)}
function bankScript(){let t='Please communicate with me in writing only. I need clear written confirmation of the payment, mandate, refund, dispute status, next step, responsible team and timescale. Telephone contact is not accessible or safe for me.';set('out',t);copyText(t)}
function demandPacing(){let r=arr(K.ready),w=arr(K.wait);let item=r[0];shell('Demand Pacing','<div class="card out">PA hides the pile. Only one demand is shown.\n\n'+(item?'One visible item:\n'+(item.a||'Item')+'\n'+(item.status||'')+'\n\nStop after this.':'No ready demand. Waiting items are not your task right now.')+'</div>'+grid([['Show Waiting Mode','queue()','primary'],['Start 48h Recovery','startRecovery()','danger'],['Open Shield','shieldIncoming()']]))}
function queue(){let r=arr(K.ready),w=arr(K.wait),h=arr(K.hidden);shell('Life Queue','<div class="card out">Ready means one possible action. Waiting means not yours right now. Hidden means not safe during low energy.</div>'+section('Ready / one step only',r)+section('Waiting for others',w)+section('Hidden / not now',h)+grid([['Shield new item','shieldIncoming()','primary'],['Demand pacing','demandPacing()']]))}
function section(t,a){return '<div class="card small"><b>'+t+'</b><br><br>'+(a.length?a.map(x=>'• '+(x.a||'Item')+' — '+(x.status||'')+'<br>'+(x.b||'')).join('<br><br>'):'None')+'</div>'}
function apptDone(){shell('Appointment Finished','<textarea id="an" rows="6" placeholder="Optional: what happened? Leave blank if tired."></textarea>'+grid([['Finish + recovery','finishAppt()','danger'],['Tell Mum','mum()']])+'<div id="out" class="card out"></div>')}
function finishAppt(){let x=v('an')||'Appointment finished. Details can be added later.';localStorage.mn_recovery_until=Date.now()+48*3600000;add(MK.line,{a:'Appointment finished - PA recovery shield',b:x});add(MK.loop,{a:'Check appointment follow-up',org:'Healthcare',status:'Waiting',b:x});add(K.hidden,{a:'Complex admin hidden during recovery',status:'Hidden',b:'Avoid forms, banking, difficult replies.'});set('out','48h recovery started. Follow-up saved.\n\n'+mumText(x))}
function startRecovery(){localStorage.mn_recovery_until=Date.now()+48*3600000;home()}
function mum(){shell('Tell Mum','<textarea id="mumIn" rows="6" placeholder="Paste what happened"></textarea>'+grid([['Paste','pasteTo("mumIn")'],['Generate Chinese','makeMum()','primary']])+'<div id="out" class="card out"></div>')}
function mumText(x){return '妈妈，简单说：\n\n'+x+'\n\n接下来请先让我休息。如果有信、电话、短信、预约或需要回复，请之后再帮我一起慢慢看。\n\n我现在可能会脑雾、累、说不清楚，不是不想说。'}
function makeMum(){let m=mumText(v('mumIn')||'今天有事情处理，我现在需要休息。');set('out',m);copyText(m);add(K.log,{a:'Chinese mum summary',b:m})}
function receive(){shieldIncoming()}
function apps(){shell('Connected apps','<div class="card small">PA shields. Mira organises. Mellow speaks.</div>'+grid([['🚪 Outside Planner','outsideMode()','primary'],['🐻 Mellow AAC','location.href="../"','primary'],['✨ Mira OS','location.href="../mira-next/"'],['🛡 Shield Incoming','shieldIncoming()'],['🎚 Tone Dial','toneDial()'],['💷 Finance Guard','financeGuard()']]))}
home();