const State={get current(){return localStorage.mellow_active_state||'HOME'},go(s){localStorage.mellow_active_state=s;renderState()},finishAppointment(){localStorage.mellow_active_state='RECOVERY';localStorage.mn_recovery_until=Date.now()+48*3600000;let item={timestamp:new Date().toISOString(),domain:'Appointment',source:'Mellow',summary:'Appointment finished. Recovery mode started.',action_taken:'Logged appointment and activated recovery mode',deadline:'No deadline',evidence_flag:true};try{let a=JSON.parse(localStorage.mira_next_timeline||'[]');a.unshift(item);localStorage.mira_next_timeline=JSON.stringify(a);localStorage.mira_next_active_session=JSON.stringify(item)}catch(e){}renderState()}};
function S(t){document.getElementById('spokenText').textContent=t;if(typeof speakText==='function')speakText(t)}
function B(label,fn,cls='btn'){return `<button class="${cls}" onclick="${fn}">${label}</button>`}
function renderState(){let c=document.getElementById('content');let s=State.current;if(s==='APPOINTMENT')return renderAppointment(c);if(s==='LETTER')return renderLetter(c);if(s==='OUTSIDE')return renderOutside(c);if(s==='RECOVERY')return renderRecovery(c);if(s==='EMERGENCY')return renderEmergency(c);renderHome(c)}
function renderHome(c){c.innerHTML=`<div class="section-card"><div class="section">What is happening?</div><p class="hint">Choose the real situation. Mellow will hide everything else.</p><div class="grid">${B('🏥 Appointment<br><small>Prepare, live AAC, finish, recovery</small>',"State.go('APPOINTMENT')")}${B('📨 Letter<br><small>Paste and detect action</small>',"State.go('LETTER')")}${B('🚪 Going outside<br><small>Leaving, shop, travel, return</small>',"State.go('OUTSIDE')")}${B('🏠 Recovery<br><small>48h low-demand mode</small>',"State.go('RECOVERY')")}${B('🚨 Emergency<br><small>Medical card and help</small>',"State.go('EMERGENCY')",'btn red')}</div></div>`}
function renderAppointment(c){c.innerHTML=`<div class="section-card"><div class="section">🏥 Appointment State</div><p class="hint">Chronological flow. Press only what matches the stage.</p><div class="grid">${B('1 Prepare<br><small>Passport, communication card, tell Mum</small>',"apptPrepare()")}${B('2 Live AAC<br><small>Use during the meeting</small>',"apptLive()",'btn purple')}${B('3 Appointment Finished<br><small>Log to Mira and start recovery</small>',"State.finishAppointment()",'btn red')}${B('Home','State.go(\'HOME\')')}</div></div>`}
function apptPrepare(){let t='Appointment preparation. Use Hospital Passport, communication card, written notes, questions, and tell Mum: I am going in now.';S(t)}
function apptLive(){document.getElementById('content').innerHTML=`<div class="section-card"><div class="section">Live AAC</div><div class="grid">${B('Hello / communication mode',"S('Hello. I am using this communication tool today because speaking and processing information can be difficult during appointments.')")}${B('One question at a time',"S('Please ask one clear specific question at a time.')")}${B('Write it down',"S('Please write that down. I need time to process and review it later.')")}${B('Processing pause',"S('I need a moment to process. Please wait before asking another question.')")}${B('Overload / speech loss',"S('I am experiencing sensory overload or speech loss. Please reduce questions and use written communication.')",'btn red')}${B('Appointment Finished',"State.finishAppointment()",'btn red')}</div></div>`}
function renderLetter(c){c.innerHTML=`<div class="section-card"><div class="section">📨 Letter State</div><p class="hint">Use PA Auto for Paste & Detect. It logs to Mira.</p><div class="grid">${B('Open PA Auto','location.href="pa/"','btn purple')}${B('Back Home','State.go(\'HOME\')')}</div></div>`}
function renderOutside(c){c.innerHTML=`<div class="section-card"><div class="section">🚪 Going Outside State</div><p class="hint">For necessary outings only. Keep it small.</p><div class="grid">${B('Leaving checklist',"S('Before going outside: phone charged, water ready, needed items ready, return plan confirmed, Mellow available, do not add extra tasks, protect recovery afterwards.')")}${B('Shop / restaurant card',"S('I have communication and processing difficulties today. Please use short clear sentences. I may need to point, use contactless payment, avoid long waiting, and finish quickly. Thank you.')")}${B('Need help',"State.go('EMERGENCY')",'btn red')}${B('Back home check',"S('Return home check: sit or lie down, drink water, food if needed, no banking, no forms, no difficult emails. Start recovery if symptoms increased.')")}${B('Start recovery',"State.go('RECOVERY')",'btn red')}</div></div>`}
function renderRecovery(c){localStorage.mn_recovery_until=localStorage.mn_recovery_until||Date.now()+48*3600000;c.innerHTML=`<div class="section-card"><div class="section">🏠 Recovery State</div><p class="hint">Complex tasks hidden. Use only safe basics.</p><div class="grid">${B('Tell Mum',"S('妈妈，我现在需要恢复。请让我休息，不要安排复杂事情。')")}${B('Water',"S('I need water please.')")}${B('Food',"S('I may need simple food please.')")}${B('Medication note',"S('Please check if any medication or nasal spray is needed.')")}${B('End recovery manually',"State.go('HOME')")}</div></div>`}
function renderEmergency(c){c.innerHTML=`<div class="section-card"><div class="section">🚨 Emergency State</div><div class="out">I have Autism, POTS, ME/CFS and communication difficulties. I may not be able to speak or stand safely. Please use short written sentences. If medically urgent, call 999.</div><div class="grid">${B('Speak emergency card',"S('I have Autism and POTS. I may faint or be unable to speak. Please do not force me to stand. Please help me sit or lie down somewhere safe. Use short written sentences. If this is a medical emergency, call 999.')",'btn red')}${B('Auto Appointment mode','location.href="auto-appointment.html"','btn red')}${B('Recovery','State.go(\'RECOVERY\')')}${B('Home','State.go(\'HOME\')')}</div></div>`}
window.addEventListener('load',renderState);
