const ME_KEY='mellow_engine_state';
const defaultEngine={activeState:'HOME',appointmentPhase:'PREPARE',goingOutPhase:'LEAVING',recovery:{isActive:false,activatedAt:null,expiresAt:null},cachedSession:null};
function loadEngine(){try{return {...defaultEngine,...JSON.parse(localStorage[ME_KEY]||'{}')}}catch(e){return {...defaultEngine}}}
function saveEngine(x){localStorage[ME_KEY]=JSON.stringify(x)}
let engine=loadEngine();
const State={
 get current(){return engine.activeState||'HOME'},
 go(s){engine.activeState=s;if(s==='RECOVERY')startRecoveryClock();saveEngine(engine);renderState()},
 phase(p){engine.appointmentPhase=p;saveEngine(engine);renderState()},
 finishAppointment(){let item={timestamp:new Date().toISOString(),domain:'Appointment',source:'Mellow State Engine',summary:'Appointment finished. Recovery mode started.',action_taken:'Logged attendance and activated recovery state',deadline:'No deadline',evidence_flag:true};try{let a=JSON.parse(localStorage.mira_next_timeline||'[]');a.unshift(item);localStorage.mira_next_timeline=JSON.stringify(a);localStorage.mira_next_active_session=JSON.stringify(item)}catch(e){}copyTextSafe('Appointment finished safely. Heading home to rest. Recovery mode started.');engine.appointmentPhase='PREPARE';engine.cachedSession=null;this.go('RECOVERY')},
 clearSession(){engine.cachedSession=null;saveEngine(engine);renderState()}
};
function startRecoveryClock(){engine.recovery={isActive:true,activatedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+48*3600000).toISOString()};localStorage.mn_recovery_until=Date.now()+48*3600000}
function S(t){document.getElementById('spokenText').textContent=t;if(typeof speakText==='function')speakText(t);copyTextSafe(t)}
function copyTextSafe(t){try{navigator.clipboard.writeText(t)}catch(e){}}
function B(label,fn,cls='btn'){return `<button class="${cls}" onclick="${fn}">${label}</button>`}
function Box(title,body){return `<div class="section-card"><div class="section">${title}</div><p class="hint">${body}</p></div>`}
function renderState(){engine=loadEngine();let c=document.getElementById('content');let s=State.current;if(s==='APPOINTMENT')return renderAppointment(c);if(s==='LETTER')return renderLetter(c);if(s==='OUTSIDE')return renderOutside(c);if(s==='RECOVERY')return renderRecovery(c);if(s==='EMERGENCY')return renderEmergency(c);renderHome(c)}
function renderHome(c){let resume='';let x=null;try{x=JSON.parse(localStorage.mira_next_active_session||'null')}catch(e){}if(x)resume=`<div class="section-card"><div class="section">Continue where I stopped</div><p class="hint">${x.domain||'Saved task'} · ${x.timestamp||''}</p><div class="grid">${B('Resume saved task',"State.go('LETTER')",'btn purple')}${B('Clear saved prompt',"localStorage.removeItem('mira_next_active_session');renderState()")}</div></div>`;c.innerHTML=resume+`<div class="section-card"><div class="section">What is happening?</div><p class="hint">Choose the real situation. Mellow hides unrelated tools.</p><div class="grid">${B('🏥 Appointment<br><small>Prepare, live AAC, finish, recovery</small>',"State.go('APPOINTMENT')")}${B('📨 Letter<br><small>Paste and detect in PA</small>',"State.go('LETTER')")}${B('🚪 Going outside<br><small>Leaving, shop, travel, return</small>',"State.go('OUTSIDE')")}${B('🏠 Recovery<br><small>48h low-demand mode</small>',"State.go('RECOVERY')")}${B('🚨 Emergency<br><small>Medical card and help</small>',"State.go('EMERGENCY')",'btn red')}</div></div>`}
function renderAppointment(c){let p=engine.appointmentPhase||'PREPARE';if(p==='LIVE')return apptLive();c.innerHTML=`<div class="section-card"><div class="section">🏥 Appointment State</div><p class="hint">Linear flow. Use Prepare, then Live AAC, then Appointment Finished.</p><div class="grid">${B('1 Prepare<br><small>Communication card, notes, tell Mum</small>',"State.phase('PREPARE');apptPrepare()")}${B('2 Live AAC<br><small>Full-screen phrases for the room</small>',"State.phase('LIVE')",'btn purple')}${B('3 Appointment Finished<br><small>Log to Mira and start recovery</small>',"State.finishAppointment()",'btn red')}${B('Home','State.go(\'HOME\')')}</div></div>`}
function apptPrepare(){let t='Appointment preparation: use Hospital Passport or communication notes. Tell Mum: I am going in now. Protect recovery time afterwards. Do not add extra tasks after the appointment.';S(t)}
function apptLive(){document.getElementById('content').innerHTML=`<div class="section-card"><div class="section">Live AAC</div><p class="hint">Use during the appointment. Press Appointment Finished when leaving.</p><div class="grid">${B('Hello / communication mode',"S('Hello. I am using this communication tool today because speaking and processing information can be difficult during appointments.')")}${B('One question at a time',"S('Please ask one clear specific question at a time. Open-ended questions are difficult for me to process.')")}${B('Write it down',"S('Please write that down. I need extra processing time and I may need to review it later with support.')")}${B('Processing pause',"S('I need a moment to process. Please wait before asking another question.')")}${B('Physical symptoms count',"S('I may describe distress through physical symptoms rather than emotion words. Please treat those descriptions as valid information.')")}${B('Overload / speech loss',"S('I am experiencing sensory overload or speech loss. Please reduce questions and use written communication.')",'btn red')}${B('Appointment Finished',"State.finishAppointment()",'btn red')}</div></div>`}
function renderLetter(c){c.innerHTML=`<div class="section-card"><div class="section">📨 Letter State</div><p class="hint">Letters and messages are handled by PA Auto. It creates Easy Read, draft reply, Mum summary, and Mira memory log.</p><div class="grid">${B('Open PA Auto','location.href="pa/"','btn purple')}${B('Back Home','State.go(\'HOME\')')}</div></div>`}
function renderOutside(c){c.innerHTML=`<div class="section-card"><div class="section">🚪 Going Outside State</div><p class="hint">For necessary outings only. You are usually out about two days per week, so this protects recovery.</p><div class="grid">${B('Leaving checklist',"S('Before going outside: phone charged, water ready, needed items ready, return plan confirmed, Mellow available, do not add extra tasks, protect recovery afterwards.')")}${B('Shop / restaurant card',"S('I have autism and communication difficulties. Today I may not be able to speak or process information quickly. Please use short clear sentences, give me time, let me point, allow contactless payment, and minimise waiting if possible because standing can make me dizzy and unwell. Thank you.')")}${B('Travel note',"S('Accessibility note: I may need seating, reduced waiting, clear written instructions, and support from a carer. Please avoid fast verbal instructions where possible.')")}${B('Need help',"State.go('EMERGENCY')",'btn red')}${B('Back home check',"S('Return home check: sit or lie down, drink water, food if needed, no banking, no forms, no difficult emails. Start recovery if symptoms increased.')")}${B('Start recovery',"State.go('RECOVERY')",'btn red')}</div></div>`}
function renderRecovery(c){if(!engine.recovery?.isActive)startRecoveryClock();saveEngine(engine);c.innerHTML=`<div class="section-card"><div class="section">🏠 Recovery State</div><p class="hint">Complex tasks hidden. Use only safe basics. Recovery window ends: ${engine.recovery.expiresAt||'48 hours from start'}.</p><div class="grid">${B('Tell Mum',"S('妈妈，我现在需要恢复。请让我休息，不要安排复杂事情。')")}${B('Water',"S('I need water please.')")}${B('Simple food',"S('I may need simple food please.')")}${B('Medication note',"S('Please check if any medication or nasal spray is needed.')")}${B('No admin reminder',"S('No banking, forms, difficult emails, or complex decisions during recovery unless urgent.')",'btn red')}${B('End recovery manually',"engine.recovery={isActive:false,activatedAt:null,expiresAt:null};saveEngine(engine);State.go('HOME')")}</div></div>`}
function renderEmergency(c){c.innerHTML=`<div class="section-card"><div class="section">🚨 Emergency State</div><div class="out">I have Autism, POTS, ME/CFS and communication difficulties. I may not be able to speak or stand safely. Please use short written sentences. If medically urgent, call 999. Allergies include Duac Once Daily Gel, pollen, onions, shellfish and oysters.</div><div class="grid">${B('Speak emergency card',"S('I have Autism and POTS. I may faint or be unable to speak. Please do not force me to stand. Please help me sit or lie down somewhere safe. Use short written sentences. If this is a medical emergency, call 999.')",'btn red')}${B('Auto Appointment mode','location.href="auto-appointment.html"','btn red')}${B('Recovery','State.go(\'RECOVERY\')')}${B('Home','State.go(\'HOME\')')}</div></div>`}
window.addEventListener('load',renderState);
