const APP=document.getElementById('app');
const P='Use clear UK English. Prefer written contact. Do not suggest phone calls unless unavoidable. Ask for written confirmation and clear next steps.';
let USER=localStorage.miraName||'Menglu';
const K={appt:'mira_appt',org:'mira_org',wait:'mira_wait',task:'mira_task',doc:'mira_doc',mem:'mira_mem',line:'mira_line'};
function A(k){try{return JSON.parse(localStorage[k]||'[]')}catch(e){return[]}}
function S(k,v){localStorage[k]=JSON.stringify(v)}
function add(k,o){let a=A(k);o.date=new Date().toLocaleString('en-GB');a.push(o);S(k,a);alert('Saved')}
function q(id){return document.getElementById(id)?.value.trim()||''}
function out(id,t){let e=document.getElementById(id);if(e)e.textContent=t}
function cp(id){navigator.clipboard.writeText(document.getElementById(id).textContent)}
function say(t,l='en-GB'){let u=new SpeechSynthesisUtterance(t);u.lang=l;u.rate=.9;speechSynthesis.cancel();speechSynthesis.speak(u)}
function btn(name,fn,cls=''){return `<button class="${cls}" onclick="${fn}">${name}</button>`}
function back(){return btn('⬅ Back','home()')}
function home(){APP.innerHTML=`<div class="card soft"><b>Mira v2.1 restored</b><p class="small">Feature set restored. Data is stored locally in this browser.</p><button class="primary" onclick="loadCheck()">🧘 Reduce My Load</button><div id="load" class="out small"></div></div><div class="card"><b>Command bar</b><input id="cmd" placeholder="appointment, reply, waiting, document, search"><button class="primary" onclick="cmd()">Run</button><div id="cmdOut" class="small out"></div></div><div id="dash" class="card small"></div>${btn('🏠 Dashboard','dash()')}${btn('⚡ Quick Actions','quick()')}${btn('🗣 Speak / AAC','speak()')}${btn('📅 Appointment Companion','appt()')}${btn('🏁 End Appointment','endAppt()')}${btn('📝 After Appointment','afterAppt()')}${btn('👥 Organisations','orgs()')}${btn('⏳ Waiting Centre','waiting()')}${btn('✅ Action Centre','tasks()')}${btn('📄 Document Centre','docs()')}${btn('✉️ Communication Hub','comm()')}${btn('🔍 Universal Search','search()')}${btn('🧪 Simulation Mode','sim()')}${btn('⚖️ Decision Helper','decide()')}${btn('🧠 Ask AI Team','team()')}${btn('🛡 Accessibility Guardian','guardian()')}${btn('🧠 Local Memory','memory()')}${btn('📝 Evidence Timeline','timeline()')}${btn('🧰 Developer Update','dev()')}${btn('🆘 Emergency','emergency()','danger')}${btn('⚙ Settings','settings()')}`;refresh()}
function refresh(){let d=document.getElementById('dash');if(d)d.textContent=`Waiting: ${A(K.wait).length} | Tasks: ${A(K.task).length} | Documents: ${A(K.doc).length} | Timeline: ${A(K.line).length}`}
function dash(){APP.innerHTML=`<h2>Dashboard</h2><div class="card out">Appointments: ${A(K.appt).length}\nOrganisations: ${A(K.org).length}\nWaiting items: ${A(K.wait).length}\nTasks: ${A(K.task).length}\nDocuments: ${A(K.doc).length}\nMemory notes: ${A(K.mem).length}\nTimeline entries: ${A(K.line).length}\n\nUse Reduce My Load for a short priority list.</div>${back()}`}
function quick(){APP.innerHTML=`<h2>Quick Actions</h2>${btn('Prepare appointment','appt()')}${btn('Draft reply','comm()')}${btn('Check waiting','waiting()')}${btn('Summarise document','docs()')}${btn('Check barrier','guardian()')}${btn('Add timeline entry','timeline()')}${back()}`}
function speak(){APP.innerHTML=`<h2>Speak / AAC</h2>${btn('▶️ Short introduction',"say('Hello. My name is '+USER+'. I may need support with communication.')")}${btn('▶️ Processing time',"say('Please give me extra time. Please ask one question at a time.')")}${btn('▶️ Written information',"say('Written information is easier for me. Please write down important information and next steps.')")}${btn('▶️ I cannot speak',"say('I cannot speak right now. Please give me time and use written communication.')")}${btn('▶️ No phone calls',"say('Please use email or written communication where possible.')")}${btn('▶️ 中文：我现在说话困难',"say('我现在说话和组织语言比较困难。请慢一点，一次说一件事。','zh-CN')")}${btn('▶️ 中文：我需要休息',"say('我需要安静休息。请不要连续追问。','zh-CN')")}${back()}`}
function appt(){APP.innerHTML=`<h2>Appointment Companion</h2><select id="type"><option>Healthcare</option><option>Benefits / welfare</option><option>Social care</option><option>Housing</option><option>Banking</option><option>Government</option><option>Education</option><option>Other</option></select><input id="who" placeholder="Person or service"><input id="time" placeholder="Time"><input id="loc" placeholder="Location"><textarea id="why" rows="4" placeholder="Reason or notes"></textarea><button onclick="makeAppt()">Generate language</button><button onclick="add(K.appt,{type:q('type'),who:q('who'),time:q('time'),loc:q('loc'),why:q('why')})">Save appointment</button><div id="apptOut" class="card out"></div>${btn('▶️ Speak generated','say(document.getElementById(\'apptOut\').textContent)')}${btn('📋 Copy','cp(\'apptOut\')')}${btn('🏁 End Appointment','endAppt()')}${btn('📝 After Appointment','afterAppt()')}${back()}`}
function makeAppt(){let type=q('type'),s=`Hello. My name is ${USER}.\n\nI have an appointment${q('who')?' with '+q('who'):''}${q('time')?' at '+q('time'):''}${q('loc')?' at '+q('loc'):''}.\n\nPlease give me time, ask one question at a time, use clear written information where possible, and confirm next steps before I leave.\n\nReason / notes:\n${q('why')}\n\n`;if(type.includes('Housing'))s+='Please confirm responsibility, timescale and written update route.';else if(type.includes('Banking'))s+='Please confirm any account, complaint, protection, refund or next step in writing.';else if(type.includes('Benefits'))s+='Please confirm what evidence is needed, who is responsible and the timescale in writing.';else s+='Please provide a short written summary and next steps.';out('apptOut',s)}
function endAppt(){APP.innerHTML=`<h2>End Appointment</h2>${btn('▶️ Ask for plain summary',"say('Before I leave, could you please summarise what we discussed today in plain language?')")}${btn('▶️ Ask for Easy Read',"say('Could you please provide Easy Read information or a short written summary where possible?')")}${btn('▶️ Ask next steps',"say('Could you please write down the next steps, who is responsible, and when I should expect to hear back?')")}${btn('▶️ Ask if anything else is needed',"say('Could you please confirm if anything needs to be sent, signed, booked, chased, or reviewed?')")}${btn('📝 After appointment summary','afterAppt()')}${back()}`}
function afterAppt(){APP.innerHTML=`<h2>After Appointment Summary</h2><textarea id="notes" rows="7" placeholder="Type or dictate short notes."></textarea><button onclick="out('sumOut','Summarise these notes. Keep only new information. Create: new information, actions agreed, responsible person, deadlines, follow-up reminders and timeline entry.\\n\\n'+P+'\\n\\nNotes:\\n'+q('notes'))">Generate ChatGPT prompt</button><button onclick="add(K.line,{type:'After appointment',note:q('notes')})">Save to timeline</button><div id="sumOut" class="card out"></div>${btn('📋 Copy','cp(\'sumOut\')')}${back()}`}
function form(title,key,a,b){APP.innerHTML=`<h2>${title}</h2><input id="a" placeholder="${a}"><textarea id="b" rows="4" placeholder="${b}"></textarea><button onclick="add('${key}',{a:q('a'),b:q('b')});list('${key}','listOut')">Save</button><button onclick="list('${key}','listOut')">Refresh</button><div id="listOut" class="card out"></div>${back()}`;list(key,'listOut')}
function list(key,id){let a=A(key);out(id,a.length?a.map((x,i)=>`${i+1}. ${x.date||''}\n${x.a||x.type||x.who||''}\n${x.b||x.note||x.why||''}`).join('\n\n'):'Nothing saved.')}
function orgs(){form('Organisations',K.org,'Organisation','Category, notes, contact rules')}
function waiting(){APP.innerHTML=`<h2>Waiting Centre</h2><input id="a" placeholder="Waiting for"><textarea id="b" rows="3" placeholder="Who / since / due date"></textarea><button onclick="add(K.wait,{a:q('a'),b:q('b')});list(K.wait,'waitOut')">Save</button><button onclick="follow()">Generate follow-up prompt</button><div id="waitOut" class="card out"></div>${back()}`;list(K.wait,'waitOut')}
function follow(){out('waitOut','Draft a short follow-up message for these waiting items. Ask for current status, responsible person, expected timescale, and written confirmation. Do not suggest phone calls.\n\n'+JSON.stringify(A(K.wait),null,2))}
function tasks(){form('Action Centre',K.task,'Task','Priority / due date / organisation')}
function docs(){APP.innerHTML=`<h2>Document Centre</h2><textarea id="doc" rows="7" placeholder="Paste document text or note."></textarea><button onclick="docPrompt()">Generate document prompt</button><button onclick="add(K.doc,{a:'Document',b:q('doc')})">Save document note</button><div id="docOut" class="card out"></div>${btn('📋 Copy','cp(\'docOut\')')}${back()}`}
function docPrompt(){out('docOut','Summarise this document. Extract sender, date, deadline, actions, risks, and filing category.\n\n'+P+'\n\nText:\n'+q('doc'))}
function comm(){APP.innerHTML=`<h2>Communication Hub</h2><select id="ctype"><option>Email reply</option><option>Formal letter</option><option>Complaint</option><option>Request adjustment</option><option>Chase update</option><option>Message to family</option></select><textarea id="msg" rows="7" placeholder="Paste message or describe what you need."></textarea><button onclick="commPrompt()">Generate drafting prompt</button><div id="commOut" class="card out"></div>${btn('📋 Copy','cp(\'commOut\')')}${back()}`}
function commPrompt(){out('commOut',`Draft this as: ${q('ctype')}. ${P}\n\nInput:\n${q('msg')}`)}
function search(){APP.innerHTML=`<h2>Universal Search</h2><input id="term" placeholder="Search local Mira data"><button onclick="findLocal()">Search local data</button><div id="findOut" class="card out"></div><textarea id="web" rows="4" placeholder="What current information needs checking?"></textarea><button onclick="out('webOut','Search current reliable sources if this may have changed. Prefer official sources. Return key facts, dates, source names, and action needed.\\n\\nQuestion:\\n'+q('web'))">Generate web search prompt</button><div id="webOut" class="card out"></div>${btn('📋 Copy web prompt','cp(\'webOut\')')}${back()}`}
function all(){return{appointments:A(K.appt),organisations:A(K.org),waiting:A(K.wait),tasks:A(K.task),documents:A(K.doc),memory:A(K.mem),timeline:A(K.line)}}
function findLocal(){let t=q('term').toLowerCase(),hits=[];Object.entries(all()).forEach(([k,v])=>v.forEach((x,i)=>{let s=JSON.stringify(x);if(s.toLowerCase().includes(t))hits.push(`${k} #${i+1}: ${s}`)}));out('findOut',hits.length?hits.join('\n\n'):'No local matches.')}
function promptScreen(title,lead){APP.innerHTML=`<h2>${title}</h2><textarea id="p" rows="7"></textarea><button onclick="out('pout','${lead.replaceAll("'","\\'")}\\n\\n'+P+'\\n\\nInput:\\n'+q('p'))">Generate prompt</button><div id="pout" class="card out"></div>${btn('📋 Copy','cp(\'pout\')')}${back()}`}
function sim(){promptScreen('Simulation Mode','Prepare me for this situation. Predict likely questions, missing information, useful evidence, accessibility risks and safe responses.')}
function decide(){promptScreen('Decision Helper','Help me compare options, risks, accessibility impact, energy cost, communication burden and missing information. Do not decide for me.')}
function team(){promptScreen('Ask AI Team','Prepare this for another AI. Share only necessary context. Ask for a second opinion, risks, missing information and practical next steps.')}
function guardian(){promptScreen('Accessibility Guardian','Review for deadlines, phone requests, ignored communication needs, missing written confirmation, unclear responsibility, risks and suggested wording.')}
function memory(){form('Local Memory',K.mem,'Memory title','Non-sensitive note')}
function timeline(){APP.innerHTML=`<h2>Evidence Timeline</h2>${btn('➕ Appointment or outing',"add(K.line,{type:'Appointment or outing',note:''});timeline()")}${btn('➕ Crash or recovery',"add(K.line,{type:'Crash or recovery',note:''});timeline()")}${btn('➕ Communication difficulty',"add(K.line,{type:'Communication difficulty',note:''});timeline()")}${btn('➕ Support needed',"add(K.line,{type:'Support needed',note:''});timeline()")}<div id="lineOut" class="card out"></div>${back()}`;list(K.line,'lineOut')}
function dev(){APP.innerHTML=`<h2>Developer Update</h2><div class="card out">Mira v2.1 restored\n\nRestored features:\nDashboard, Quick Actions, AAC, Appointment, End Appointment, After Appointment, Organisations, Waiting, Tasks, Documents, Communication, Search, Simulation, Decision, AI Team, Guardian, Memory, Timeline, Emergency, Settings.\n\nRule: do not replace working features until the new version is ready.</div><button onclick="exportData()">Export backup</button><textarea id="backup" rows="7"></textarea>${back()}`}
function exportData(){let e=document.getElementById('backup');if(e)e.value=JSON.stringify(all(),null,2)}
function emergency(){APP.innerHTML=`<h2>Emergency</h2>${btn('▶️ I cannot speak',"say('I cannot speak right now. Please give me time and use written communication.')",'danger')}${btn('▶️ I feel unwell',"say('I feel unwell and may need to sit or lie down safely.')")}${btn('▶️ Reduce overload',"say('Please reduce noise, lights, questions and pressure. I need a quiet place.')")}${back()}`}
function settings(){APP.innerHTML=`<h2>Settings</h2><input id="nm" value="${USER}"><button onclick="localStorage.miraName=q('nm');USER=q('nm');alert('Saved')">Save name</button><button onclick="exportData()">Export local data</button><textarea id="backup" rows="7"></textarea>${back()}`}
function loadCheck(){let d=all();out('load',`Urgent check\n\nWaiting items: ${d.waiting.length}\nTasks: ${d.tasks.length}\nAppointments: ${d.appointments.length}\nDocuments: ${d.documents.length}\nTimeline entries: ${d.timeline.length}\n\nSuggested order:\n1. Check Waiting Centre.\n2. Check Action Centre.\n3. Prepare appointments.\n4. Summarise new documents.\n5. Add timeline only if something changed.`)}
function cmd(){let c=q('cmd').toLowerCase();if(c.includes('wait'))waiting();else if(c.includes('task'))tasks();else if(c.includes('reply')||c.includes('email'))comm();else if(c.includes('appoint')||c.includes('prepare'))appt();else if(c.includes('document')||c.includes('letter'))docs();else if(c.includes('search')||c.includes('find'))search();else if(c.includes('guard'))guardian();else out('cmdOut','Try: appointment, reply, waiting, task, document, search, guardian.')}if('serviceWorker'in navigator){navigator.serviceWorker.register('sw.js').catch(()=>{})}home();