const app=document.getElementById('app');
const state={theme:localStorage.getItem('mira-theme')||'light',size:localStorage.getItem('mira-size')||'normal',section:null,shield:false,task:null,planned:null,warning:false};
function save(){localStorage.setItem('mira-theme',state.theme);localStorage.setItem('mira-size',state.size)}
function apply(){document.body.className=`theme-${state.theme} size-${state.size} ${isRecovery()?'recovery-layout':''}`;save()}
function grid(items){return `<div class="grid">${items.map(x=>`<button class="${x[2]||''}" onclick="${x[1]}">${x[0]}</button>`).join('')}</div>`}
function isRecovery(){return Number(localStorage.miraRecoveryUntil||0)>Date.now()}
function hoursLeft(){return Math.max(0,Math.ceil((Number(localStorage.miraRecoveryUntil||0)-Date.now())/3600000))}
function triggerRecovery(){localStorage.miraRecoveryUntil=Date.now()+48*3600000;state.theme='sensory-dark';state.shield=false;state.task=null;home()}
function endRecovery(){delete localStorage.miraRecoveryUntil;home()}
function evalTask(title,load){state.task={title,load};state.planned=null;state.warning=false;state.shield=true;render()}
function confirmShield(){if(state.planned===false){state.warning=true;render();return}state.shield=false;state.task=null;render()}
function config(){return `<header class="system-config-bar"><div class="config-group"><label>Theme</label><button class="${state.theme==='light'?'active':''}" onclick="state.theme='light';render()">☀️ Light</button><button class="${state.theme==='sensory-dark'?'active':''}" onclick="state.theme='sensory-dark';render()">🌙 Sensory Dark</button><button class="${state.theme==='soft-warm'?'active':''}" onclick="state.theme='soft-warm';render()">🌅 Soft Warm</button><button class="${state.theme==='night'?'active':''}" onclick="state.theme='night';render()">🌃 Night</button></div><div class="config-group"><label>Text Size</label><button class="${state.size==='normal'?'active':''}" onclick="state.size='normal';render()">Normal</button><button class="${state.size==='large'?'active':''}" onclick="state.size='large';render()">Large</button><button class="${state.size==='xlarge'?'active':''}" onclick="state.size='xlarge';render()">Extra Large</button></div></header>`}
function shield(){if(!state.shield||!state.task)return '';let brains='🧠'.repeat(state.task.load)+'☆'.repeat(5-state.task.load);return `<section class="decision-shield-overlay"><div class="shield-card"><h2>🛡 Decision Shield</h2><p>High-demand task detected:</p><div class="shield-target-box">${state.task.title}</div><div>Estimated load: ${brains}</div><p><b>Is post-task recovery planned?</b></p><div class="shield-button-split"><button class="${state.planned===true?'selected-yes':''}" onclick="state.planned=true;state.warning=false;render()">YES, prepared</button><button class="${state.planned===false?'selected-no':''}" onclick="state.planned=false;render()">NO, not planned</button></div>${state.warning?'<div class="critical-warning-box"><b>⚠ High crash risk</b><p>Do not execute this safely without a recovery buffer. Cancel, postpone, reduce scope, or ask for support.</p></div>':''}<div class="shield-action-row"><button onclick="state.shield=false;render()">Cancel task</button><button onclick="confirmShield()">Confirm and proceed</button></div></div></section>`}
function recoveryBanner(){return isRecovery()?`<div class="sticky-recovery-banner"><div class="banner-header">🌙 Recovery Mode Active</div><div class="banner-timer">${hoursLeft()} hours remaining</div><div class="banner-rules"><b>Avoid:</b> phone calls, banking, forms, difficult decisions, new admin.</div><button class="banner-exit-btn" onclick="endRecovery()">End Recovery Mode</button></div>`:''}
function disclosure(id,title,content){let open=state.section===id;return `<div class="disclosure-wrapper"><button class="disclosure-toggle" onclick="state.section=state.section==='${id}'?null:'${id}';render()">${open?'▼':'▶'} ${title}</button>${open?`<div class="disclosure-content">${content}</div>`:''}</div>`}
function standard(){return `<main class="single-column-flow"><h2>Mira One</h2><button class="card-critical" onclick="triggerRecovery()">🚨 Start 48-hour recovery mode</button>${disclosure('comm','Communication Channels',`<p class="small">Written-only contact profile active.</p><button onclick="evalTask('Reply to formal DWP or official letter',4)">Launch document simplifier 🧠×4</button><button onclick="location.href='../mira-next/'">Open Mira Plus</button>`)}${disclosure('appt','Appointments and Audits',`<button onclick="evalTask('Process hospital appointment letter',3)">Review hospital letter 🧠×3</button><button onclick="evalTask('Prepare for new professional meeting',4)">Two-stage preparation 🧠×4</button>`)}${disclosure('finance','Financial Protections',`<button onclick="evalTask('Verify bank outgoings or financial safety',5)">Check banking ledger 🧠×5</button><button onclick="location.href='../mira-next/'">Open Financial Safeguard</button>`)}${disclosure('system','System Tracker',`<button onclick="evalTask('Chase Trust / UC / bank response',3)">Chase written response 🧠×3</button><textarea id="sys" rows="5" placeholder="Agency / task / responsible person / status"></textarea><button onclick="saveSystem()">Save system note</button><div id="sysout" class="card small"></div>`)}${disclosure('shield','Decision Shield Tests',`<button onclick="evalTask('Read complex benefit letter',4)">Benefit letter 🧠×4</button><button onclick="evalTask('Send formal complaint or escalation',5)">Formal escalation 🧠×5</button><button onclick="evalTask('Low energy note only',1)">Low energy note 🧠×1</button>`)}</main>`}
function recovery(){return `<main class="single-column-flow"><h2>Low-Sensory Critical Commands Only</h2><button class="card-critical" onclick="say('I need help right now. I may have reduced speech, brain fog, dizziness, severe fatigue or sensory overload. Please reduce questions and help me rest somewhere quiet.')">🆘 Help</button><button onclick="location.href='../'">🚨 Emergency AAC</button><button onclick="say('I need water or help with hydration.')">💧 Water</button><button onclick="say('I need something simple to eat if available.')">🍽 Food</button><button onclick="say('I need to rest. Please reduce demands and noise.')">😴 Rest</button><button onclick="location.href='../mira-next/'">📝 Notes</button><button onclick="endRecovery()">End recovery mode</button></main>`}
function saveSystem(){let a=JSON.parse(localStorage.miraSystemNotes||'[]');a.push({date:new Date().toLocaleString('en-GB'),text:document.getElementById('sys').value});localStorage.miraSystemNotes=JSON.stringify(a);document.getElementById('sysout').textContent='Saved system note.'}
function say(t){if('speechSynthesis'in window){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang='en-GB';u.rate=.82;speechSynthesis.speak(u)}else alert(t)}
function home(){render()}
function appointment(){evalTask('Prepare or attend appointment',4)}
function aac(){location.href='../'}
function workspace(){location.href='../mira-next/'}
function brain(){evalTask('Use AI to process complex information',3)}
function render(){apply();app.innerHTML=recoveryBanner()+`<div class="dashboard-container">${!isRecovery()?config():''}${isRecovery()?recovery():standard()}</div>`+shield()}
render();