keys.loop='mn_loop';keys.ev='mn_ev';keys.sys='mn_sys';keys.doc2='mn_doc2';
function recOn(){return Number(localStorage.mn_recovery_until||0)>Date.now()}
function recHours(){return Math.max(0,Math.ceil((Number(localStorage.mn_recovery_until||0)-Date.now())/3600000))}
function startRec(){localStorage.mn_recovery_until=Date.now()+48*3600000;add(keys.line,{a:'48h recovery mode started',b:'Low demand mode after high-load event'});home()}
function stopRec(){delete localStorage.mn_recovery_until;home()}
function maxHome(){if(recOn())return recoveryMode();app.innerHTML=`<div class="card soft"><b>🐻 Mira Next</b><p class="small">Executive-functioning engine. Keep the current Mira interface; add protection, tracking and evidence.</p>${grid([['🛡 Decision Shield','decisionShield()','primary'],['🌙 48h Recovery','startRec()','danger']])}<div class="small">Waiting: ${arr(keys.wait).length} | Tasks: ${arr(keys.task).length} | Open loops: ${arr(keys.loop).filter(x=>x.status!=='Closed').length} | Evidence: ${arr(keys.ev).length}</div></div>`+
group('Protection engine',[['🛡 Decision Shield','decisionShield()','primary'],['📋 Paste & Simplify','pasteSimplify()','primary'],['🔁 Open Loops','openLoops()'],['🧭 System Tracker','systemTracker2()'],['📚 Evidence Builder','evidenceBuilder()'],['⚡ Admin Engine','adminEngine2()']])+
group('Existing Mira tools',[['🪫 Energy Budget','energyBudget()'],['📨 Communication Vault','vault()'],['🧾 Easy Read','easyRead()'],['🚨 Emergency Passport','passport()','danger'],['🏦 Financial Safeguard','financeSafe()'],['⚡ Quick Capture','capture()']])+
group('Appointments and records',[['📅 Prepare','appointment()'],['🏁 End Appointment','endAppt2()'],['📝 After Appointment','afterAppt()'],['📜 Timeline','timeline()'],['📄 Documents','docs()'],['🔎 Search','searchAll()']])}
function home(){maxHome()}
function decisionShield(){app.innerHTML=`<h2>Decision Shield</h2><div class="card small">Use before high-load admin, benefits, banking, letters, appointments or difficult decisions.</div><input id="dsTask" placeholder="What are you about to do?"><select id="dsLoad"><option value="1">Low 🧠☆☆☆☆</option><option value="2">Medium 🧠🧠☆☆☆</option><option value="3">High 🧠🧠🧠☆☆</option><option value="4">Very high 🧠🧠🧠🧠☆</option><option value="5">Maximum 🧠🧠🧠🧠🧠</option></select><select id="dsRest"><option value="yes">Recovery planned</option><option value="no">No recovery planned</option></select>${grid([['Check risk','dsCheck()','primary'],['Save as task','dsTaskSave()'],['Start recovery','startRec()','danger']])}<div id="out" class="card out"></div>${back()}`}
function dsCheck(){let load=+v('dsLoad'),rest=v('dsRest'),task=v('dsTask')||'Task',brains='🧠'.repeat(load)+'☆'.repeat(5-load);let m=`Task: ${task}\nEstimated load: ${brains}\n\n`;if(load>=4&&rest==='no')m+='⚠ HIGH CRASH RISK. Do not continue without recovery, support, reduced scope, or postponement.';else if(load>=3)m+='Caution. Use written support, stop point, and recovery afterwards.';else m+='Lower risk. Still pace and stop early.';set('out',m);add(keys.line,{a:'Decision Shield: '+task,b:m})}
function dsTaskSave(){add(keys.task,{a:v('dsTask')||'Decision Shield task',b:'Check risk before doing this'});set('out','Saved to Tasks.')}
function pasteSimplify(){app.innerHTML=`<h2>Paste & Simplify</h2><div class="card small">Copy a letter/email first. Then tap paste. If iPhone blocks clipboard access, tap inside the box and paste manually.</div>${grid([['📋 One-tap paste','readClip()','primary'],['📄 Simplify and log','simplifyDoc()']])}<textarea id="docin" rows="9" placeholder="Paste letter or email here"></textarea><div id="out" class="card out"></div>${back()}`}
async function readClip(){let t=document.getElementById('docin');try{t.value=await navigator.clipboard.readText();t.focus()}catch(e){t.focus();set('out','Clipboard blocked. Tap inside the box and paste manually.')}}
function docKind(x){let s=x.toLowerCase();if(s.includes('nhs')||s.includes('hospital')||s.includes('clinic'))return 'Health / NHS';if(s.includes('pip')||s.includes('universal credit')||s.includes('dwp'))return 'Benefits';if(s.includes('bank')||s.includes('payment')||s.includes('account'))return 'Bank / money';if(s.includes('repair')||s.includes('housing')||s.includes('tenant'))return 'Housing';return 'General'}
function simplifyDoc(){let x=v('docin'),kind=docKind(x),large=x.length>3000;let m=`Detected: ${kind}\nEffort: ${large?'High load. Read in sections.':'Moderate load.'}\n\nEasy Read prompt:\n1. What this means\n2. What action is required\n3. Strict deadline\n4. Risk if I do nothing\n5. Safest next step\n\nText:\n${x}`;set('out',m);add(keys.doc2,{a:kind+' document',b:m});add(keys.line,{a:'Document logged: '+kind,b:large?'Large document. Decision Shield recommended.':'Document simplified.'});if(large)add(keys.loop,{a:'Review large '+kind+' document',org:kind,status:'Needs follow-up',b:'Use pacing and Decision Shield.'})}
function openLoops(){app.innerHTML=`<h2>Open Loops</h2><input id="la" placeholder="Loop title"><input id="lo" placeholder="Organisation / person"><select id="ls"><option>Open</option><option>Waiting</option><option>Needs follow-up</option><option>Closed</option></select><textarea id="ln" rows="3" placeholder="Next step / notes"></textarea>${grid([['Save loop','saveLoop()','primary'],['Show loops','listLoops()']])}<div id="out" class="card out"></div>${back()}`;listLoops()}
function saveLoop(){add(keys.loop,{a:v('la'),org:v('lo'),status:v('ls'),b:v('ln')});listLoops()}
function listLoops(){let a=arr(keys.loop);set('out',a.length?a.map((x,i)=>`${i+1}. ${x.a}\n${x.org||''}\nStatus: ${x.status||''}\n${x.b||''}\n${x.date||''}`).join('\n\n'):'No open loops saved yet.')}
function systemTracker2(){app.innerHTML=`<h2>System Tracker</h2><input id="sa" placeholder="Agency / contact"><input id="st" placeholder="Current task / ask"><input id="sr" placeholder="Responsible party"><select id="ss"><option>Pending written response</option><option>In progress</option><option>Needs follow-up</option><option>Confirmed active</option><option>Closed</option></select><textarea id="sn" rows="3" placeholder="Last update"></textarea>${grid([['Save system item','saveSys2()','primary'],['Generate follow-up','sysFollow()']])}<div id="out" class="card out"></div>${back()}`;sysList()}
function saveSys2(){add(keys.sys,{a:v('sa'),task:v('st'),resp:v('sr'),status:v('ss'),b:v('sn')});add(keys.loop,{a:v('st'),org:v('sa'),status:v('ss'),b:v('sn')});sysList()}
function sysList(){let a=arr(keys.sys);set('out',a.length?a.map((x,i)=>`${i+1}. ${x.a}\nTask: ${x.task}\nResponsible: ${x.resp}\nStatus: ${x.status}\n${x.b}`).join('\n\n'):'No system tracker items yet.')}
function sysFollow(){let a=arr(keys.sys)[0]||{};set('out',`Please provide a written update.\n\nAgency/contact: ${a.a||''}\nCurrent task: ${a.task||''}\nResponsible party: ${a.resp||''}\n\nPlease confirm current status, named responsibility, next step, timescale, and whether anything is needed from me. Please use written communication.`)}
function evidenceBuilder(){app.innerHTML=`<h2>Evidence Builder</h2><input id="ea" placeholder="Event / issue"><select id="et"><option>Appointment impact</option><option>Communication barrier</option><option>Recovery crash</option><option>Support needed</option><option>System delay</option></select><textarea id="en" rows="4" placeholder="What happened and functional impact"></textarea>${grid([['Save evidence','saveEv()','primary'],['Build summary','evSummary()']])}<div id="out" class="card out"></div>${back()}`;evList()}
function saveEv(){add(keys.ev,{a:v('ea'),type:v('et'),b:v('en')});add(keys.line,{a:'Evidence: '+v('ea'),b:v('en')});evList()}
function evList(){let a=arr(keys.ev);set('out',a.length?a.map((x,i)=>`${i+1}. ${x.type}\n${x.a}\n${x.b}\n${x.date}`).join('\n\n'):'No evidence saved yet.')}
function evSummary(){let a=arr(keys.ev);set('out','Evidence summary\n\n'+a.map(x=>`- ${x.date}: ${x.type}. ${x.a}. ${x.b}`).join('\n'))}
function adminEngine2(){app.innerHTML=`<h2>Admin Engine</h2><select id="ak"><option value="care">Care coordination</option><option value="benefits">Benefits / UC</option><option value="bank">Bank safety</option><option value="health">Healthcare adjustments</option><option value="utility">Priority services</option></select>${btn('Generate document','makeAdmin2()','primary')}<textarea id="aout" rows="12" readonly></textarea>${btn('Copy','navigator.clipboard.writeText(document.getElementById(\'aout\').value)')}${back()}`}
function makeAdmin2(){let k=v('ak'),base=`Formal access and communication profile\n\nName: Menglu Liu\nLocation: Banbridge, County Down\nSupport: Kun Shi\n\nAccess needs:\n- Written communication where possible.\n- No reliance on phone calls.\n- One question at a time.\n- Clear next steps, named responsibility and timescale.\n- Supported communication is not independent functioning.\n\n`;let body={care:'Please provide a light-touch review and accessible coordination pathway. Please confirm responsible person, next step and timescale.',benefits:'Please provide written guidance about appointee or administrative support. Please confirm status, evidence needed and timescale.',bank:'Please confirm account safety actions, unusual payments, mandates or next steps in writing. Please avoid phone-only contact.',health:'Please record reasonable adjustments: written communication, one question at a time, prepared notes or AAC, and written next steps.',utility:'Please add priority services and written contact needs. Please confirm registration and support arrangements.'}[k];document.getElementById('aout').value=base+body;add(keys.doc2,{a:'Generated admin: '+k,b:base+body})}
function recoveryMode(){app.innerHTML=`<h2>48h Recovery Mode</h2><div class="card out">Low-sensory critical-only mode.\n${recHours()} hours remaining.\nAvoid phone calls, banking, complex forms, difficult decisions and new admin.</div>${grid([['I need help now',"say('I need help now. Please reduce questions, help me rest somewhere quiet, and use written communication.')",'danger'],['Water',"say('I need water or help with hydration.')"],['Food',"say('I need something simple to eat if available.')"],['Rest',"say('I need to rest. Please reduce demands and noise.')"],['Emergency Passport','passport()','danger'],['End recovery','stopRec()']])}`}
function endAppt2(){app.innerHTML=`<h2>End Appointment</h2><div class="card small">Start recovery and log delayed-collapse risk.</div>${grid([['Start 48h recovery','startRec()','danger'],['Written next steps',"say('Please write down the next steps, who is responsible, and the timescale.')"],['After appointment summary','afterAppt()']])}${back()}`}
home();