keys.stage='mn_stage';keys.system='mn_system';keys.crash='mn_crash';
function activeRecovery(){return Number(localStorage.mn_recovery_until||0)>Date.now()}
function hoursLeft(){return Math.ceil((Number(localStorage.mn_recovery_until||0)-Date.now())/3600000)}
function startRecovery(){localStorage.mn_recovery_until=Date.now()+48*3600000;add(keys.crash,{a:'48 hour recovery started',b:'Low demand mode'});recoveryMode()}
function stopRecovery(){delete localStorage.mn_recovery_until;home()}
function home(){if(activeRecovery())return recoveryMode();app.innerHTML=`<div class="card soft"><b>🐻 Mira One</b><p class="small">Executive-functioning buffer. Protect energy before tasks.</p>${grid([['🚪 Two-Stage Gate','stageGate()','primary'],['🌙 48h Recovery','startRecovery()','danger']])}<div id="today" class="card small">${counts()}</div></div><div class="card"><b>Command bar</b><input id="cmd" placeholder="stage, recovery, system, energy, vault, easy read"><button class="primary" onclick="cmd()">Run</button><div id="cmdOut" class="small out"></div></div>`+
group('Executive engine',[['🚪 Two-Stage Gate','stageGate()','primary'],['🌙 48h Recovery Mode','startRecovery()','danger'],['🧭 System Tracker','systemTracker()','primary'],['🪫 Energy Budget','energyBudget()'],['📨 Communication Vault','vault()'],['🧾 Easy Read','easyRead()']])+
group('Core tools',[['⚡ Quick Capture','capture()'],['🚨 Emergency Passport','passport()','danger'],['🪪 Care Card','careCard()'],['⭐ Favourite phrases','favourites()'],['📅 Appointment','appointment()'],['🏁 End Appointment','endAppt()']])+
group('Records',[['👥 Organisations','orgs()'],['⏳ Waiting','waiting()'],['✅ Tasks','tasks()'],['📄 Documents','docs()'],['📜 Timeline','timeline()'],['💾 Backup','backup()']])}
function stageGate(){app.innerHTML=`<h2>Two-Stage Gate</h2><div class="card small">Stage 1 sends a pre-meeting pack. Stage 2 is only used after the person confirms they read it.</div><input id="agency" placeholder="Professional or agency"><textarea id="reason" rows="4" placeholder="Why they are involved"></textarea>${grid([['Generate Stage 1','stageOne()','primary'],['Mark read / unlock','stageRead()'],['Open Stage 2','stageTwo()'],['Show saved','stageList()']])}<div id="out" class="card out"></div>${grid([['📋 Copy','copy(\'out\')'],['✅ Save task','taskFromOut()'],['⏳ Save waiting','waitingFromOut()']])}${back()}`;stageList()}
function stageOne(){let agency=v('agency')||'professional';let text=`STAGE 1 PRE-MEETING PACK\n\nFor: ${agency}\n\nPurpose:\n${v('reason')||'Please read before any appointment.'}\n\nMain point:\nI may understand information but still be unable to coordinate the process independently. My barriers include real-time communication, fatigue, sensory load, follow-up, admin and delayed deterioration.\n\nPlease use written communication, one question at a time, clear responsibility, clear timescale and written next steps.\n\nPlease confirm in writing that this has been read before the next stage.`;set('out',text);add(keys.stage,{a:agency,b:'Stage 1 generated. Waiting for read confirmation.'})}
function stageRead(){add(keys.stage,{a:v('agency')||'professional',b:'Read confirmed. Stage 2 unlocked.'});set('out','Stage 2 unlocked.')}
function stageTwo(){set('out','STAGE 2 MEETING PREP\n\nStart by confirming they read Stage 1.\n\nAsk:\n1. What is your role?\n2. What are you responsible for?\n3. What is the next written step?\n4. Who owns follow-up?\n5. What is the timescale?\n\nDo not re-explain everything from scratch if Stage 1 was not read.')}
function stageList(){let a=arr(keys.stage);set('out',a.length?a.map((x,i)=>`${i+1}. ${x.date}\n${x.a}\n${x.b}`).join('\n\n'):'No gates saved yet.')}
function recoveryMode(){app.innerHTML=`<h2>🌙 48h Recovery Mode</h2><div class="card out">Recovery window active.\n\nTime left: ${hoursLeft()} hours.\n\nDo not start non-urgent admin, letters, banking, benefit tasks, new decisions or complex communication.</div>${grid([['🆘 I need help now','helpNow()','danger'],['🚨 Emergency Passport','passport()','danger'],['🗣 Cannot speak',"say('I cannot speak right now. Please use written communication and give me time.')"],['🍵 Basic needs','basicNeeds()'],['End recovery mode','stopRecovery()']])}`}
function helpNow(){app.innerHTML=`<h2>I need help now</h2><div id="out" class="card out">I am in a recovery window after a high-demand event. I may have reduced speech, brain fog, dizziness, severe fatigue or sensory overload. Please reduce questions, help me rest somewhere quiet, and seek urgent help if I appear medically unsafe.</div>${grid([['▶️ Speak','say(document.getElementById(\'out\').textContent)'],['📋 Copy','copy(\'out\')'],['Back','recoveryMode()']])}`}
function basicNeeds(){app.innerHTML=`<h2>Basic needs</h2>${grid([['Water',"say('I need water or help with hydration.')"],['Food',"say('I need something simple to eat if available.')"],['Lie down',"say('I need to lie down or recline safely.')",'danger'],['Quiet',"say('The noise is too much. I need a quieter place.')"],['Back','recoveryMode()']])}`}
function systemTracker(){app.innerHTML=`<h2>System Tracker</h2><input id="sa" placeholder="Agency / contact"><input id="st" placeholder="Current task / ask"><input id="sr" placeholder="Responsible party"><select id="ss"><option>Pending written response</option><option>In progress</option><option>Confirmed active</option><option>Needs follow-up</option><option>Blocked</option><option>Closed</option></select><textarea id="sn" rows="3" placeholder="Last update / notes"></textarea>${grid([['Save item','systemSave()','primary'],['Show tracker','systemList()'],['Follow-up prompt','systemPrompt()']])}<div id="out" class="card out"></div>${back()}`;systemList()}
function systemSave(){add(keys.system,{a:v('sa'),task:v('st'),resp:v('sr'),status:v('ss'),b:v('sn')});systemList()}
function systemList(){let a=arr(keys.system);set('out',a.length?a.map((x,i)=>`${i+1}. ${x.a}\nTask: ${x.task||''}\nResponsible: ${x.resp||''}\nStatus: ${x.status||''}\nUpdate: ${x.b||''}`).join('\n\n'):'No system items saved yet.')}
function systemPrompt(){set('out','Draft a written follow-up asking for current status, named responsibility, next step, timescale and written confirmation.\n\n'+JSON.stringify(arr(keys.system),null,2))}
function endAppt(){app.innerHTML=`<h2>End Appointment</h2><div class="card small">Start 48h recovery to prevent overdoing after apparent coping.</div>${grid([['Start 48h recovery','startRecovery()','danger'],['Plain summary',"say('Before I leave, could you summarise what we discussed in plain language?')"],['Written next steps',"say('Please write down next steps, responsibility and timescale.')"],['After appointment summary','afterAppt()']])}${back()}`}
const oldCmd=cmd;cmd=function(){let c=v('cmd').toLowerCase();if(c.includes('stage')||c.includes('gate'))stageGate();else if(c.includes('recovery')||c.includes('collapse'))startRecovery();else if(c.includes('system')||c.includes('tracker'))systemTracker();else oldCmd()}
home();