function osArr(k){try{return JSON.parse(localStorage[k]||'[]')}catch(e){return[]}}
function osAdd(k,o){let a=osArr(k);o.date=new Date().toLocaleString('en-GB');a.unshift(o);localStorage[k]=JSON.stringify(a)}
function osV(id){return document.getElementById(id)?.value.trim()||''}
function osSet(id,t){let e=document.getElementById(id);if(e)e.textContent=t}
function osType(s){s=(s||'').toLowerCase();if(/nhs|hospital|clinic|gp|appointment|rheumatology|dentist/.test(s))return 'Health';if(/pip|universal credit|uc|dwp|benefit|lcwra/.test(s))return 'Benefits';if(/bank|aib|payment|direct debit|refund|chargeback|scam/.test(s))return 'Money';if(/repair|housing|lotus|leak|plumber|electric|smoke|alarm/.test(s))return 'Housing';if(/mum|mother|family|wechat|妈妈/.test(s))return 'Family';return 'General'}
async function osPaste(id){let e=document.getElementById(id);try{e.value=await navigator.clipboard.readText();e.focus()}catch(err){e.focus();osSet('out','Paste manually.')}}
function home(){let loops=osArr('mn_loop').filter(x=>x.status!=='Closed').length,wait=osArr('mn_wait').length,rec=Number(localStorage.mn_recovery_until||0)>Date.now();app.innerHTML=`<div class="card soft"><b>🐻 Mira OS</b><p class="small">One place to handle letters, emails, appointments, evidence, recovery and follow-up with fewer repeated steps.</p><div class="small">Open loops: ${loops} | Waiting: ${wait} | Recovery: ${rec?'ON':'OFF'}</div>${grid([['🪄 Handle This','handleThis()','primary'],['🌙 Recovery','recoveryPanel()','danger']])}</div>`+
group('One-tap workflows',[['🪄 Handle This','handleThis()','primary'],['📥 Intake Hub','intakeHub()','primary'],['🏁 Appointment Finished','endApptPolished()','danger'],['🇨🇳 Tell Mum','mumQuick()'],['📎 Smart Attachments','smartAttachments()'],['🧭 Waiting Mode','waitingMode()']])+
group('Knowledge system',[['🔎 Memory Search','universalSearchPolished()','primary'],['🕸 Relationship Map','relationshipMap()'],['📜 Timeline Graph','timelineGraph()'],['📚 Evidence Pack','evidencePack()'],['🔁 Open Loops','openLoopEngine()'],['🧾 Document Pipeline','documentPipeline()']])+
group('Safe admin',[['🛡 Decision Shield','decisionShield()','primary'],['⚡ Admin Generator','adminGenerator()'],['🧭 System Tracker','systemTrackerPolished()'],['📨 Communication Vault','vault()'],['🚨 Emergency Passport','passport()','danger'],['🤖 Mira Brain','brain()']])}
function handleThis(){app.innerHTML=`<h2>Handle This</h2><div class="card small">Paste anything once. Mira files it, drafts a reply, adds timeline, creates an open loop if needed, and suggests the safest next action.</div><textarea id="htext" rows="9" placeholder="Paste email, letter, message, appointment text, repair update, bank text..."></textarea>${grid([['Paste','osPaste(\'htext\')'],['Handle this','runHandleThis()','primary']])}<div id="out" class="card out"></div>${back()}`}
function runHandleThis(){let x=osV('htext'),type=osType(x),needs=/reply|required|deadline|appointment|confirm|book|by |before|within|urgent/i.test(x),high=/appointment|hospital|bank|scam|pip|universal credit|repair|leak|alarm/i.test(x);let reply=`Dear Team,\n\nThank you for your message. Please continue in writing and confirm the next step, who is responsible, and the timescale. Because of my disability-related communication and processing difficulties, written communication is safer and more accessible than telephone contact.\n\nKind regards,\nMenglu Liu`;let out=`Handled by Mira\n\nType: ${type}\nAction: ${needs?'Review only if needed':'No action now / waiting'}\nLoad: ${high?'High - use pacing':'Moderate'}\n\nMira did:\n✓ filed document\n✓ added timeline\n✓ created open loop if needed\n✓ drafted safe reply\n✓ added evidence if useful\n\nEasy Read:\n1. What this means:\n2. Action needed:\n3. Deadline:\n4. Safest next step:\n\nSuggested reply:\n${reply}`;osSet('out',out);osAdd('mn_doc2',{a:'Handled item: '+type,b:out+'\n\nOriginal:\n'+x});osAdd('mn_line',{a:'Handled: '+type,b:x});if(needs)osAdd('mn_loop',{a:'Review '+type+' item',org:type,status:'Needs review',b:'Created by Handle This.'});if(high)osAdd('mn_ev',{a:'High-load admin item: '+type,type:'Admin / communication load',b:'Handled through Mira to reduce repeated processing.'})}
function waitingMode(){let loops=osArr('mn_loop').filter(x=>/Waiting|wait|review|follow/i.test(x.status||''));app.innerHTML=`<h2>Waiting Mode</h2><div class="card out">This screen separates waiting from work.\n\nIf another organisation needs to act, it is not your unfinished task.</div><div class="card small">${loops.length?loops.map((x,i)=>`${i+1}. <b>${x.a||''}</b><br>${x.org||''} · ${x.status||''}<br>${x.b||''}<br><br>`).join(''):'Nothing is waiting.'}</div>${grid([['Add waiting item','openLoopEngine()','primary'],['Generate chase email','chaseLoop()'],['Back home','home()']])}`}
function smartAttachments(){app.innerHTML=`<h2>Smart Attachments</h2><select id="att"><option>Healthcare</option><option>Benefits / UC / PIP</option><option>Bank</option><option>Housing repair</option><option>Social care</option></select>${grid([['Make checklist','makeAttachList()','primary'],['Open documents','documentPipeline()']])}<div id="out" class="card out"></div>${back()}`}
function makeAttachList(){let t=osV('att'),base=['Hospital Passport / communication needs','Relevant timeline entries','Previous email or reference number','Clear request for written next steps'];let extra={ 'Healthcare':['Medication / allergy note if relevant','Questions list','Symptom impact summary'], 'Benefits / UC / PIP':['Evidence summary','Functional impact examples','Support needs statement'], 'Bank':['Transaction date/amount only','Written-only support request','Fraud/scam concern wording'], 'Housing repair':['Photos/screenshots if available','Date first reported','Safety risk and access needs'], 'Social care':['Care coordination need','Support worker / named contact request','Why family cannot manage alone'] }[t]||[];osSet('out','Before sending to '+t+':\n\n'+base.concat(extra).map(x=>'□ '+x).join('\n'))}
function relationshipMap(){app.innerHTML=`<h2>Relationship Map</h2><div class="card out">Healthcare\n├ GP / surgery\n├ PCC / Deirdre\n├ Rheumatology\n├ OT / Trust\n└ Dentist / oral medicine\n\nBenefits\n├ PIP\n├ Universal Credit / Mollie\n└ DfC / appointee pathway\n\nMoney\n├ AIB\n├ LCS / 1st Locate\n└ Accountant support\n\nHousing\n├ Lotus Homes\n├ Repairs / plumber\n└ Priority services\n\nFamily\n├ Mum / Kun Shi\n└ Dad / driver support</div>${grid([['Search person/service','universalSearchPolished()','primary'],['Add system item','systemTrackerPolished()']])}${back()}`}
function timelineGraph(){let a=osArr('mn_line').slice(0,20);app.innerHTML=`<h2>Timeline Graph</h2><div class="card out">${a.length?a.map(x=>'● '+(x.date||'')+'\n│ '+(x.a||'')+'\n│ '+(x.b||'').slice(0,120)).join('\n│\n'):'No timeline entries yet.'}</div>${grid([['Add evidence','evidencePack()','primary'],['Search timeline','universalSearchPolished()']])}${back()}`}
function mumQuick(){app.innerHTML=`<h2>Tell Mum</h2><textarea id="mumText" rows="6" placeholder="Paste what happened. Leave blank for simple recovery message."></textarea>${grid([['Paste','osPaste(\'mumText\')'],['Generate Chinese','makeMumQuick()','primary']])}<div id="out" class="card out"></div>${back()}`}
function makeMumQuick(){let x=osV('mumText')||'今天有事情处理，我现在需要休息。';let m=`妈妈，今天简单说：\n\n${x}\n\n接下来：请先让我休息。如果有信、电话、预约或需要回复，请之后再慢慢帮我看。\n\n我现在可能会脑雾、累、说不清楚，不是不想说。之后1-2天可能会更累。`;osSet('out',m);navigator.clipboard.writeText(m).catch(()=>{});osAdd('mn_line',{a:'Chinese summary for mum',b:m})}
home();