function safeArr(k){try{return JSON.parse(localStorage[k]||'[]')}catch(e){return[]}}
function safeAdd(k,o){let a=safeArr(k);o.date=new Date().toLocaleString('en-GB');a.unshift(o);localStorage[k]=JSON.stringify(a)}
function txt(id){return document.getElementById(id)?.value.trim()||''}
function html(id,t){let e=document.getElementById(id);if(e)e.innerHTML=t}
function text(id,t){let e=document.getElementById(id);if(e)e.textContent=t}
function home(){let loops=safeArr('mn_loop').filter(x=>x.status!=='Closed').length,docs=safeArr('mn_doc2').length+safeArr('mn_doc').length,rec=Number(localStorage.mn_recovery_until||0)>Date.now();app.innerHTML=`<div class="card soft"><b>🐻 Mira Next</b><p class="small">Main workspace for documents, appointments, evidence, open loops and low-demand admin.</p><div class="small">Open loops: ${loops} | Documents: ${docs} | Recovery: ${rec?'ON':'OFF'}</div>${grid([['🧠 Mira Brain','brain()','primary'],['🛡 Decision Shield','decisionShield()','primary']])}</div>`+
group('Most useful now',[['📥 Intake Hub','intakeHub()','primary'],['🧾 Document Pipeline','documentPipeline()','primary'],['🔁 Open Loop Engine','openLoopEngine()'],['📚 Evidence Pack','evidencePack()'],['🌙 Recovery Mode','recoveryPanel()','danger'],['📨 Communication Vault','vault()']])+
group('Daily admin',[['📅 Appointment Command','appointmentCommand()'],['🏁 End Appointment','endApptPolished()'],['🧭 System Tracker','systemTrackerPolished()'],['⚡ Admin Generator','adminGenerator()'],['🔎 Universal Search','universalSearchPolished()'],['💾 Export Backup','backup()']])+
group('Existing tools',[['🪫 Energy Budget','energyBudget()'],['🚨 Emergency Passport','passport()','danger'],['🏦 Financial Safeguard','financeSafe()'],['🗣 AAC','aac()'],['⭐ Favourite Phrases','favourites()'],['🪪 Care Card','careCard()']])}
function intakeHub(){app.innerHTML=`<h2>Intake Hub</h2><div class="card small">Paste anything received. Mira sorts it, drafts a safe response, logs it, and creates a quiet open loop if needed.</div><textarea id="intake" rows="8" placeholder="Paste email, letter, appointment text, message, repair note or bank text"></textarea>${grid([['Paste from clipboard','pasteInto(\'intake\')'],['Process intake','processIntake()','primary']])}<div id="out" class="card out"></div>${back()}`}
async function pasteInto(id){let e=document.getElementById(id);try{e.value=await navigator.clipboard.readText();e.focus()}catch(err){e.focus();text('out','Clipboard blocked. Tap inside the box and paste manually.')}}
function classify(s){s=(s||'').toLowerCase();if(s.includes('nhs')||s.includes('hospital')||s.includes('clinic')||s.includes('gp')||s.includes('appointment'))return 'Health';if(s.includes('pip')||s.includes('universal credit')||s.includes('dwp')||s.includes('benefit'))return 'Benefits';if(s.includes('bank')||s.includes('payment')||s.includes('account')||s.includes('direct debit'))return 'Money';if(s.includes('repair')||s.includes('housing')||s.includes('tenant')||s.includes('lotus'))return 'Housing';return 'General'}
function processIntake(){let x=txt('intake'),type=classify(x),action=/deadline|reply|required|by |before|appointment|book|confirm/i.test(x);let reply=`Dear Team,\n\nThank you for your message. Because of my disability-related communication and processing difficulties, please continue in writing and confirm the next step, who is responsible, and the timescale.\n\nKind regards,\nMenglu Liu`;let out=`Type: ${type}\nAction level: ${action?'Needs review':'File / waiting'}\n\nMira did:\n✓ Easy Read headings\n✓ Safe reply draft\n✓ Timeline log\n✓ Document record\n✓ Open loop if needed\n\nEasy Read:\n1. What this means:\n2. Action needed:\n3. Deadline:\n4. Safest next step:\n\nDraft reply:\n${reply}`;text('out',out);safeAdd('mn_line',{a:'Intake: '+type,b:x});safeAdd('mn_doc2',{a:'Intake document: '+type,b:out});if(action)safeAdd('mn_loop',{a:'Review '+type+' item',org:type,status:'Needs review',b:'Created from Intake Hub.'})}
function documentPipeline(){app.innerHTML=`<h2>Document Pipeline</h2><textarea id="docpipe" rows="9" placeholder="Paste document text"></textarea>${grid([['Paste','pasteInto(\'docpipe\')'],['Summarise + file','runDocPipe()','primary'],['Generate reply','docReply()']])}<div id="out" class="card out"></div>${back()}`}
function runDocPipe(){let x=txt('docpipe'),type=classify(x),large=x.length>2500;let out=`Detected: ${type}\nEffort: ${large?'High. Read in sections.':'Moderate.'}\n\nSummary structure:\n1. Sender / organisation\n2. What this means\n3. Action required\n4. Deadline\n5. Risk if ignored\n6. Safest next step`;text('out',out);safeAdd('mn_doc2',{a:'Document pipeline: '+type,b:out+'\n\nOriginal:\n'+x});safeAdd('mn_line',{a:'Document filed: '+type,b:large?'Large document':'Document filed'})}
function docReply(){let type=classify(txt('docpipe'));text('out',`Dear Team,\n\nThank you for your ${type.toLowerCase()} message. Please confirm the next step, who is responsible, and the timescale in writing. Because of my communication and processing difficulties, written information is safer and more accessible than telephone contact.\n\nKind regards,\nMenglu Liu`)}
function openLoopEngine(){app.innerHTML=`<h2>Open Loop Engine</h2><input id="olTitle" placeholder="What is open?"><input id="olOrg" placeholder="Who / organisation"><select id="olStatus"><option>Waiting</option><option>Needs review</option><option>Needs follow-up</option><option>Blocked</option><option>Closed</option></select><textarea id="olNote" rows="3" placeholder="Next step / what they owe me"></textarea>${grid([['Save loop','saveOpenLoop()','primary'],['Generate chase','chaseLoop()']])}<div id="out" class="card out"></div>${back()}`;listOpenLoops()}
function saveOpenLoop(){safeAdd('mn_loop',{a:txt('olTitle'),org:txt('olOrg'),status:txt('olStatus'),b:txt('olNote')});listOpenLoops()}
function listOpenLoops(){let a=safeArr('mn_loop');text('out',a.length?a.map((x,i)=>`${i+1}. ${x.a||''}\n${x.org||''} · ${x.status||''}\n${x.b||''}\n${x.date||''}`).join('\n\n'):'No open loops saved.')}
function chaseLoop(){let a=safeArr('mn_loop')[0]||{};text('out',`Dear Team,\n\nPlease provide a written update about: ${a.a||'[issue]'}.\n\nPlease confirm current status, who is responsible, what the next step is, and the expected timescale.\n\nKind regards,\nMenglu Liu`)}
function evidencePack(){app.innerHTML=`<h2>Evidence Pack</h2><input id="evTitle" placeholder="Event / issue"><select id="evType"><option>Appointment impact</option><option>Communication barrier</option><option>Recovery crash</option><option>Support needed</option><option>System delay</option></select><textarea id="evNote" rows="4" placeholder="What happened, what support was needed, consequence afterwards"></textarea>${grid([['Save evidence','saveEvidencePolished()','primary'],['Build summary','buildEvidenceSummary()']])}<div id="out" class="card out"></div>${back()}`}
function saveEvidencePolished(){safeAdd('mn_ev',{a:txt('evTitle'),type:txt('evType'),b:txt('evNote')});safeAdd('mn_line',{a:'Evidence: '+txt('evTitle'),b:txt('evNote')});text('out','Saved to Evidence and Timeline.')}
function buildEvidenceSummary(){let a=safeArr('mn_ev');text('out','Evidence summary\n\n'+(a.length?a.map(x=>`- ${x.date}: ${x.type}. ${x.a}. ${x.b}`).join('\n'):'No evidence saved.'))}
function recoveryPanel(){let on=Number(localStorage.mn_recovery_until||0)>Date.now(),hrs=Math.ceil((Number(localStorage.mn_recovery_until||0)-Date.now())/3600000);app.innerHTML=`<h2>Recovery Mode</h2><div class="card out">Status: ${on?'ON':'OFF'}${on?'\nHours left: '+hrs:''}\n\nWhen active, avoid forms, banking, difficult replies, phone calls and new admin.</div>${grid([['Start 48h recovery','startRecoveryPolished()','danger'],['End recovery','endRecoveryPolished()'],['I need help text','recoveryHelp()','primary']])}<div id="out" class="card out"></div>${back()}`}
function startRecoveryPolished(){localStorage.mn_recovery_until=Date.now()+48*3600000;safeAdd('mn_line',{a:'48h recovery started',b:'Started from Mira Next'});recoveryPanel()}
function endRecoveryPolished(){delete localStorage.mn_recovery_until;recoveryPanel()}
function recoveryHelp(){text('out','I am in a recovery period. I may have reduced speech, brain fog, dizziness, fatigue or sensory overload. Please reduce questions, use written communication, and help me rest somewhere quiet.')}
function appointmentCommand(){app.innerHTML=`<h2>Appointment Command</h2>${grid([['Prepare appointment','appointment()','primary'],['Start appointment script','doctorMode()'],['End appointment safely','endApptPolished()','danger'],['Tell Mum after','mumSummaryFromMira()']])}<div id="out" class="card out"></div>${back()}`}
function endApptPolished(){app.innerHTML=`<h2>End Appointment</h2><textarea id="endnote" rows="5" placeholder="Optional notes. Leave blank if tired."></textarea>${grid([['Finish + start recovery','finishAppointmentPolished()','danger'],['Ask written next steps',"say('Please write down the next steps, who is responsible, and the timescale before I leave.')"],['Copy closing checklist','copyClosingChecklist()']])}<div id="out" class="card out"></div>${back()}`}
function finishAppointmentPolished(){let note=txt('endnote')||'Appointment finished. Details can be added later.';localStorage.mn_recovery_until=Date.now()+48*3600000;safeAdd('mn_line',{a:'Appointment finished - recovery started',b:note});safeAdd('mn_loop',{a:'Check appointment follow-up',org:'Healthcare',status:'Waiting',b:note});text('out','Appointment logged. 48h recovery started. Follow-up loop created.')} 
function copyClosingChecklist(){let t='Before I leave, please write down: what was decided, who is responsible, what I need to do, timescale, referrals/tests, and how follow-up will happen in writing.';text('out',t);navigator.clipboard.writeText(t).catch(()=>{})}
function mumSummaryFromMira(){text('out','妈妈，今天预约/事情结束了。接下来请先让我休息。如果有信、预约、回复或材料，我们之后再慢慢看。我现在可能会脑雾、累、说不清楚，不是不想说。')}
function systemTrackerPolished(){app.innerHTML=`<h2>System Tracker</h2><input id="syOrg" placeholder="Organisation / person"><input id="syTask" placeholder="Current task / ask"><input id="syResp" placeholder="Responsible person"><select id="syStatus"><option>Waiting</option><option>In progress</option><option>Needs follow-up</option><option>Blocked</option><option>Closed</option></select><textarea id="syNote" rows="3" placeholder="Last update"></textarea>${grid([['Save tracker item','saveTrackerPolished()','primary'],['Make follow-up','trackerFollowup()']])}<div id="out" class="card out"></div>${back()}`;trackerList()}
function saveTrackerPolished(){safeAdd('mn_sys',{a:txt('syOrg'),task:txt('syTask'),resp:txt('syResp'),status:txt('syStatus'),b:txt('syNote')});safeAdd('mn_loop',{a:txt('syTask'),org:txt('syOrg'),status:txt('syStatus'),b:txt('syNote')});trackerList()}
function trackerList(){let a=safeArr('mn_sys');text('out',a.length?a.map((x,i)=>`${i+1}. ${x.a}\nTask: ${x.task}\nResponsible: ${x.resp}\nStatus: ${x.status}\n${x.b}`).join('\n\n'):'No system tracker items.')}
function trackerFollowup(){let a=safeArr('mn_sys')[0]||{};text('out',`Please provide a written update.\n\nOrganisation: ${a.a||''}\nCurrent task: ${a.task||''}\nResponsible person: ${a.resp||''}\n\nPlease confirm status, next step and timescale.`)}
function adminGenerator(){app.innerHTML=`<h2>Admin Generator</h2><select id="adm"><option value="health">Healthcare adjustments</option><option value="benefits">Benefits / UC</option><option value="care">Care coordination</option><option value="bank">Bank safety</option><option value="housing">Housing repair</option></select>${grid([['Generate','makeAdminPolished()','primary'],['Copy output','navigator.clipboard.writeText(document.getElementById(\'out\').textContent)']])}<div id="out" class="card out"></div>${back()}`}
function makeAdminPolished(){let k=txt('adm'),base='Name: Menglu Liu\n\nAccess needs:\n- Written communication where possible.\n- No reliance on phone calls.\n- One question at a time.\n- Clear next steps, named responsibility and timescale.\n\n';let body={health:'Please record reasonable adjustments and provide written summaries of decisions and next steps.',benefits:'Please provide written guidance about appointee or administrative support and confirm current status, evidence needed and timescale.',care:'Please provide a light-touch review and accessible coordination pathway. Please confirm responsible person and next written step.',bank:'Please confirm account safety actions, unusual payments, mandates, refunds or next steps in writing.',housing:'Please confirm repair status, safety risk, responsibility, access arrangements and timescale in writing.'}[k];text('out',base+body)}
function universalSearchPolished(){app.innerHTML=`<h2>Universal Search</h2><input id="sq" placeholder="Search local Mira data"><button onclick="doUniversalSearch()">Search</button><div id="out" class="card out"></div>${back()}`}
function doUniversalSearch(){let q=txt('sq').toLowerCase(),keys2=['mn_loop','mn_doc2','mn_doc','mn_line','mn_ev','mn_sys','mn_task','mn_wait'],hits=[];keys2.forEach(k=>safeArr(k).forEach(x=>{let s=JSON.stringify(x);if(s.toLowerCase().includes(q))hits.push(s)}));text('out',hits.length?hits.join('\n\n'):'No matches.')}
home();