const app=document.getElementById('app');
const base='Use clear UK English. Prefer written contact. Do not suggest phone calls unless unavoidable. Ask for written confirmation, named responsibility and clear next steps.';
const keys={ap:'mn_appt',org:'mn_org',wait:'mn_wait',task:'mn_task',doc:'mn_doc',line:'mn_line',mem:'mn_mem'};
let name=localStorage.mn_name||'Menglu';
function arr(k){try{return JSON.parse(localStorage[k]||'[]')}catch(e){return[]}}
function saveArr(k,a){localStorage[k]=JSON.stringify(a)}
function add(k,o){let a=arr(k);o.date=new Date().toLocaleString('en-GB');a.push(o);saveArr(k,a);alert('Saved')}
function v(id){return document.getElementById(id)?.value.trim()||''}
function set(id,t){let e=document.getElementById(id);if(e)e.textContent=t}
function say(t,l='en-GB'){if(!('speechSynthesis'in window)){alert(t);return}let u=new SpeechSynthesisUtterance(t);u.lang=l;u.rate=.82;speechSynthesis.cancel();speechSynthesis.speak(u)}
function copy(id){navigator.clipboard.writeText(document.getElementById(id).textContent)}
function esc(s){return String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function btn(t,fn,c=''){return `<button class="${c}" onclick="${fn}">${t}</button>`}
function grid(items){return `<div class="grid">${items.map(x=>btn(x[0],x[1],x[2]||'')).join('')}</div>`}
function group(title,items){return `<div class="section-title">${title}</div>${grid(items)}`}
function back(){return btn('⬅ Back','home()')}
function counts(){return `Waiting: ${arr(keys.wait).length} | Tasks: ${arr(keys.task).length} | Documents: ${arr(keys.doc).length} | Timeline: ${arr(keys.line).length}`}
function home(){app.innerHTML=`<div class="card soft"><b>🐻 Mira Dashboard</b><p class="small">Choose the lowest-effort next step. Everyday tools stay near the top.</p>${grid([['✨ Reduce My Load','reduceLoad()','primary'],['🧠 Mira Brain','brain()','primary']])}<div id="load" class="out small"></div></div><div class="card"><b>Command bar</b><input id="cmd" placeholder="appointment, letter, reply, waiting, document, emergency">${btn('Run','cmd()','primary')}<div id="cmdOut" class="small out"></div></div><div id="today" class="card small"></div>`+
group('One tap modes',[['🏥 Reception Mode','reception()'],['👩‍⚕️ Doctor Mode','doctorMode()'],['📄 Letter Mode','letterMode()'],['🗣 AAC','aac()'],['🆘 Emergency','emergency()','danger'],['⚡ Quick Actions','quick()']])+
group('Appointments',[['📅 Prepare','appointment()'],['🏁 End Appointment','endAppt()'],['📝 After Appointment','afterAppt()'],['📜 Timeline','timeline()']])+
group('Admin and records',[['👥 Organisations','orgs()'],['⏳ Waiting','waiting()'],['✅ Tasks','tasks()'],['📄 Documents','docs()']])+
group('Writing and AI',[['✉️ Communication','communication()'],['🛡 Guardian','guardian()'],['⚖️ Decision','decision()'],['🧪 Simulation','simulation()'],['🧠 AI Team','aiTeam()'],['🔎 Search','searchAll()']])+
group('Data',[['💾 Backup','backup()'],['🧷 Memory','memory()'],['⚙ Settings','settings()']]);refresh()}
function refresh(){let el=document.getElementById('today');if(el)el.textContent=counts()}
function dashboard(){app.innerHTML=`<h2>Dashboard</h2><div class="card out">${counts()}\n\nSuggested order:\n1. Safety or emergency\n2. Urgent tasks\n3. Waiting items\n4. Appointment preparation\n5. Document or letter summary\n6. Timeline update\n\nTip: use Mira Brain when you do not know which tool to choose.</div>${back()}`}
function quick(){app.innerHTML=`<h2>Quick Actions</h2>${grid([['🏥 Reception mode','reception()'],['👩‍⚕️ Doctor mode','doctorMode()'],['📄 Letter mode','letterMode()'],['✉️ Draft reply','communication()'],['⏳ Check waiting','waiting()'],['📄 Summarise document','docs()'],['🛡 Check barrier','guardian()'],['📜 Record timeline','timeline()']])}${back()}`}
function aac(){app.innerHTML=`<h2>AAC</h2><div class="card small">Longer messages are designed to help other people understand your communication needs, support needs and hidden difficulties.</div>${group('Core explanation',[['▶️ Full introduction',"say('Hello. My name is '+name+'. I use this communication assistant because speaking, processing spoken information and organising answers can become difficult for me. I may understand more than I can say out loud. Please speak to me directly, give me extra time, ask one question at a time, and write down important information.')"],['▶️ Supported not independent',"say('If I answer using this device, prepared notes, my mother, or extra time, this does not mean I can manage the same situation independently, quickly, repeatedly, or by phone. This is supported communication.')"],['▶️ Processing time',"say('Please give me extra time. I am not ignoring you. I am processing the question and trying to organise my answer. Please do not repeat or add more information while I am thinking.')"],['▶️ Written information',"say('Written information is easier and safer for me. Please write down important information, decisions, responsibilities, deadlines and next steps so I can understand and follow up later.')"],['▶️ Cannot speak',"say('I cannot speak right now. Please give me time, reduce pressure, and use written communication. Please do not assume I am refusing or not cooperating.')"],['▶️ No phone calls',"say('Please do not rely on phone calls. Phone calls can cause overload, missed information and unsafe misunderstandings. Please use email, text, letter or written notes where possible.')"]])}${group('中文',[['▶️ 说话困难',"say('我现在说话和组织语言比较困难。请慢一点，一次只说一件事。请给我时间处理信息，不要连续追问。','zh-CN')"],['▶️ 需要安静',"say('我现在有点过载，需要安静休息。请减少声音、问题和压力。','zh-CN')"],['▶️ 不是不配合',"say('我不是故意不回答，也不是不配合。我需要更多时间处理信息，最好用文字沟通。','zh-CN')"]])}${back()}`}
function reception(){app.innerHTML=`<h2>Reception Mode</h2><div id="out" class="card out">Hello. My name is ${name}. I may have difficulty with spoken communication, fast questions, phone-style conversation and processing information in a busy environment.\n\nPlease speak slowly, ask one thing at a time, and give me time to answer. Written information is easier and safer for me.\n\nIf there are forms, waiting instructions, changes, delays or next steps, please write them down or show them clearly.\n\nMy mother may support me, but please speak to me directly. I remain the decision-maker.</div>${grid([['▶️ Speak','say(document.getElementById(\'out\').textContent)'],['📋 Copy','copy(\'out\')'],['📅 Appointment prep','appointment()'],['🆘 Emergency','emergency()','danger']])}${back()}`}
function doctorMode(){app.innerHTML=`<h2>Doctor Mode</h2><div id="out" class="card out">Hello. I have prepared information because I may not be able to explain everything accurately in real time.\n\nPlease allow me to use prepared notes before detailed questions. Please ask one question at a time and provide written next steps.\n\nI may look calm even when I am overwhelmed, in pain, dizzy, cognitively fatigued, or losing speech. Please do not judge my difficulty only by appearance.\n\nPlease explain each step before examination or touch. I may need pauses because of dizziness, fatigue, pain, sensory sensitivity or slow processing.\n\nBefore I leave, please summarise what has been decided, who is responsible, what I should do next, and when I should expect follow-up.</div>${grid([['▶️ Speak','say(document.getElementById(\'out\').textContent)'],['📋 Copy','copy(\'out\')'],['🏁 End appointment','endAppt()'],['📝 After appointment','afterAppt()']])}${back()}`}
function letterMode(){app.innerHTML=`<h2>Letter Mode</h2><textarea id="letter" rows="8" placeholder="Paste letter, email, form text or photo transcription here"></textarea>${grid([['Analyse letter','makeLetter()','primary'],['Save as document','saveLetter()']])}<div id="out" class="card out"></div>${grid([['📋 Copy','copy(\'out\')'],['✅ Create task','taskFromOut()'],['📜 Timeline note','lineFromOut()']])}${back()}`}
function makeLetter(){set('out','Summarise this letter in Easy Read style. Extract: sender, date, purpose, deadlines, actions needed, risks, evidence needed, who is responsible, and safest next step. Do not suggest phone calls unless unavoidable.\n\nLetter text:\n'+v('letter'))}
function saveLetter(){add(keys.doc,{a:'Letter / document',b:v('letter')})}
function taskFromOut(){add(keys.task,{a:'Action from Mira output',b:document.getElementById('out').textContent})}
function lineFromOut(){add(keys.line,{a:'Timeline note from Mira output',b:document.getElementById('out').textContent})}
function appointment(){app.innerHTML=`<h2>Appointment</h2><select id="type"><option>Healthcare</option><option>Benefits / welfare</option><option>Social care</option><option>Housing</option><option>Banking</option><option>Government</option><option>Education</option><option>Other</option></select><input id="who" placeholder="Person or service"><input id="time" placeholder="Time"><input id="loc" placeholder="Location"><textarea id="why" rows="4" placeholder="Reason or notes"></textarea><div class="row">${btn('Generate','makeAppt()')}${btn('Save','saveAppt()')}</div><div id="out" class="card out"></div>${grid([['▶️ Speak','say(document.getElementById(\'out\').textContent)'],['📋 Copy','copy(\'out\')'],['🏥 Reception','reception()'],['👩‍⚕️ Doctor','doctorMode()']])}${back()}`}
function makeAppt(){let type=v('type'),s=`Hello. My name is ${name}.\n\nI have an appointment${v('who')?' with '+v('who'):''}${v('time')?' at '+v('time'):''}${v('loc')?' at '+v('loc'):''}.\n\nI may need support with communication, processing, fatigue, dizziness or sensory overload. Please speak slowly, ask one question at a time, allow pauses, and provide written information. I may use prepared notes or this communication assistant.\n\n`;if(v('why'))s+=`Reason / notes:\n${v('why')}\n\n`;if(type.includes('Housing'))s+='Please confirm the issue, responsibility, timescale, safety risk, access arrangements and written update route.';else if(type.includes('Banking'))s+='Please confirm account protection, complaint status, refund or next step in writing. Please do not rely on phone calls.';else if(type.includes('Benefits'))s+='Please confirm what evidence is needed, who is responsible, the timescale, and what happens next in writing.';else if(type.includes('Healthcare'))s+='Please provide a short written summary, clinical plan, referrals, tests, medication or non-medication advice, risks, and next steps before I leave.';else s+='Please provide a short written summary and next steps before I leave.';set('out',s)}
function saveAppt(){add(keys.ap,{type:v('type'),who:v('who'),time:v('time'),loc:v('loc'),why:v('why')})}
function endAppt(){app.innerHTML=`<h2>End Appointment</h2>${grid([['▶️ Plain summary',"say('Before I leave, could you please summarise what we discussed today in plain language?')"],['▶️ Easy Read',"say('Could you please provide Easy Read information or a short written summary where possible?')"],['▶️ Next steps',"say('Could you please write down the next steps, who is responsible, and when I should expect to hear back?')"],['▶️ Anything else needed',"say('Could you please confirm if anything needs to be sent, signed, booked, chased, or reviewed?')"],['After appointment summary','afterAppt()']])}${back()}`}
function afterAppt(){promptScreen('After Appointment','notes','Summarise these notes. Keep only new information. Create: new information, actions agreed, responsible person, deadlines, follow-up reminders, and timeline entry.')}
function form(title,k,a,b){app.innerHTML=`<h2>${title}</h2><input id="a" placeholder="${a}"><textarea id="b" rows="4" placeholder="${b}"></textarea>${grid([['Save',`add('${k}',{a:v('a'),b:v('b')});list('${k}')`],['Show saved',`list('${k}')`]])}<div id="list" class="card out"></div>${back()}`;list(k)}
function orgs(){form('Organisations',keys.org,'Organisation','Category, contact rules, written route, notes')}
function waiting(){app.innerHTML=`<h2>Waiting</h2><input id="a" placeholder="Waiting for"><textarea id="b" rows="4" placeholder="Who, since date, due date, notes"></textarea>${grid([['Save waiting item',`add('${keys.wait}',{a:v('a'),b:v('b')});list('${keys.wait}')`],['Follow-up prompt','followPrompt()']])}<div id="list" class="card out"></div>${back()}`;list(keys.wait)}
function tasks(){form('Tasks',keys.task,'Task','Priority, due date, organisation')}
function docs(){app.innerHTML=`<h2>Documents</h2><input id="a" placeholder="Title or source"><textarea id="b" rows="6" placeholder="Paste document text or notes"></textarea>${grid([['Save document note',`add('${keys.doc}',{a:v('a'),b:v('b')});list('${keys.doc}')`],['Document prompt','docPrompt()'],['Letter mode','letterMode()']])}<div id="list" class="card out"></div>${back()}`;list(keys.doc)}
function communication(){promptScreen('Communication','comm','Draft a clear UK English message. Include accessibility needs only when relevant. Do not suggest phone calls. Ask for written confirmation and next steps where useful.')}
function guardian(){promptScreen('Accessibility Guardian','guard','Check this for deadlines, requests to phone, unclear responsibility, missing written confirmation, ignored communication needs, risks, and suggested wording.')}
function decision(){promptScreen('Decision Helper','dec','Help me compare options without making the decision for me. Include risks, accessibility impact, energy cost, missing information and safest next step.')}
function simulation(){promptScreen('Simulation Mode','sim','Prepare me for this situation. Predict likely questions, missing information, useful evidence, accessibility risks and safe responses.')}
function aiTeam(){promptScreen('Ask AI Team','team','Prepare this for another AI. Share only necessary context. Ask for second opinion, risks, missing information and practical next steps.')}
function promptScreen(title,id,lead){app.innerHTML=`<h2>${title}</h2><textarea id="${id}" rows="7" placeholder="Paste or type here"></textarea>${btn('Generate prompt',`set('pout','${lead}\n\n${base}\n\nInput:\n'+v('${id}'))`)}<div id="pout" class="card out"></div>${grid([['📋 Copy','copy(\'pout\')'],['✅ Save as task','taskFromPout()']])}${back()}`}
function taskFromPout(){add(keys.task,{a:'Task from AI prompt',b:document.getElementById('pout').textContent})}
function timeline(){app.innerHTML=`<h2>Timeline</h2>${grid([['➕ Appointment or outing',"quick('Appointment or outing')"],['➕ Crash or recovery',"quick('Crash or recovery')"],['➕ Communication difficulty',"quick('Communication difficulty')"],['➕ Support needed',"quick('Support needed')"],['Show saved timeline',`list('${keys.line}')`]])}<div id="list" class="card out"></div>${back()}`;list(keys.line)}
function memory(){form('Memory',keys.mem,'Memory title','Non-sensitive note')}
function workspace(){app.innerHTML=`<h2>Workspace</h2>${group('Records',[['👥 Organisations','orgs()'],['⏳ Waiting','waiting()'],['✅ Tasks','tasks()'],['📄 Documents','docs()'],['📜 Timeline','timeline()'],['💾 Backup','backup()']])}${group('Common workspaces',[['🏥 Health','setWorkspace(\'Health / medical\')'],['🏛 Benefits','setWorkspace(\'Benefits / DWP / UC / PIP\')'],['🏠 Housing','setWorkspace(\'Housing / repairs\')'],['🏦 Bank','setWorkspace(\'Banking / bills / safety\')']])}<div id="workout" class="card out"></div>${back()}`}
function setWorkspace(t){set('workout',`Workspace: ${t}\n\nUse this to collect related appointments, documents, waiting items, tasks, contacts, risks and next steps.\n\nSuggested sections:\n- Main issue\n- Who is responsible\n- Written contact route\n- What is waiting\n- Deadline\n- Evidence\n- Next safest action`)}
function brain(){app.innerHTML=`<h2>Mira Brain</h2><div class="card small">Type what happened. Mira creates a structured action plan you can copy into ChatGPT or save into Mira.</div><textarea id="brainin" rows="8" placeholder="Example: I got a hospital letter / I need to reply to DWP / I had an appointment"></textarea>${grid([['Generate plan','makeBrain()','primary'],['Letter mode','letterMode()'],['Appointment mode','appointment()'],['Communication mode','communication()']])}<div id="brainout" class="card out"></div>${grid([['📋 Copy','copy(\'brainout\')'],['✅ Save task','brainTask()'],['📜 Save timeline','brainLine()']])}${back()}`}
function makeBrain(){let x=v('brainin');set('brainout',`Mira Brain Plan\n\nSituation:\n${x}\n\n1. What this probably is:\n- Identify the organisation, purpose, deadline and risk.\n\n2. Lowest-effort next step:\n- Do not phone unless unavoidable.\n- Use written communication.\n- Ask for written confirmation.\n\n3. Extract:\n- Who sent it / who is responsible\n- Date received\n- Deadline\n- Action needed\n- Evidence needed\n- Risk if delayed\n\n4. Create from this:\n- One task\n- One waiting item if a reply is needed\n- One timeline entry if it affects health, benefits, housing, finance or support\n\n5. Prompt for ChatGPT:\n${base}\n\nPlease analyse this situation, identify risks, missing information, deadline, safest next step, and draft any message needed.\n\nInput:\n${x}`)}
function brainTask(){add(keys.task,{a:'Mira Brain action',b:document.getElementById('brainout').textContent})}
function brainLine(){add(keys.line,{a:'Mira Brain timeline',b:document.getElementById('brainout').textContent})}
function searchAll(){app.innerHTML=`<h2>Universal Search</h2><input id="q" placeholder="Search local Mira data">${btn('Search','findLocal()')}<div id="res" class="card out"></div><textarea id="web" rows="4" placeholder="What current information needs checking?"></textarea>${btn('Generate web search prompt','webPrompt()')}<div id="webout" class="card out"></div>${back()}`}
function settings(){app.innerHTML=`<h2>Settings</h2><input id="nm" value="${name}">${btn('Save name',"localStorage.mn_name=v('nm');name=v('nm');alert('Saved')")}${back()}`}
function emergency(){app.innerHTML=`<h2>Emergency</h2><div class="card out">Use only when safety, fainting, shutdown, urgent health symptoms, overload or communication loss is happening.</div>${grid([['▶️ I cannot speak',"say('I cannot speak right now. Please give me time, reduce pressure, and use written communication. Please do not assume I am refusing or not cooperating.')",'danger'],['▶️ I feel faint',"say('I think I may faint. Please help me sit or lie down safely, reduce stimulation, and get medical help if needed.')",'danger'],['▶️ Reduce overload',"say('Please reduce noise, lights, questions and pressure. I need a quiet place with fewer demands.')"],['▶️ Read my information',"say('Please read the information on this device. It explains my communication and health support needs.')"]])}${back()}`}
function list(k){let a=arr(k);set('list',a.length?a.map((x,i)=>`${i+1}. ${x.date||''}\n${x.a||x.type||''}\n${x.b||x.why||''}`).join('\n\n'):'Nothing saved.')}
function quick(t){add(keys.line,{a:t,b:''});list(keys.line)}
function followPrompt(){set('list','Draft a short follow-up message for these waiting items. Ask for written confirmation, current status, named responsibility and expected timescale.\n\n'+base+'\n\n'+JSON.stringify(arr(keys.wait),null,2))}
function docPrompt(){set('list','Summarise this document. Extract sender, date, deadlines, actions needed, risks and filing category.\n\n'+base+'\n\n'+v('b'))}
function findLocal(){let q=v('q').toLowerCase(),hits=[];Object.values(keys).forEach(k=>arr(k).forEach((x,i)=>{let s=JSON.stringify(x);if(s.toLowerCase().includes(q))hits.push(`${k} #${i+1}: ${s}`)}));set('res',hits.length?hits.join('\n\n'):'No local matches.')}
function webPrompt(){set('webout','Search current reliable sources if this may have changed. Prefer official sources. Return key facts, source names, dates and action needed.\n\nQuestion:\n'+v('web'))}
function reduceLoad(){let urgent=arr(keys.task).filter(x=>JSON.stringify(x).toLowerCase().includes('urgent')).length;set('load',`Urgent tasks: ${urgent}\nWaiting items: ${arr(keys.wait).length}\nAppointments: ${arr(keys.ap).length}\nDocuments: ${arr(keys.doc).length}\nTimeline entries: ${arr(keys.line).length}\n\nSuggested next step:\n${urgent?'Open Tasks and handle urgent item.':arr(keys.wait).length?'Open Waiting and check follow-up.':arr(keys.ap).length?'Open Appointment prep.':'Use Mira Brain for the next unclear item.'}`)}
function backup(){app.innerHTML=`<h2>Backup</h2>${btn('Export data','exportData()')}<textarea id="backup" rows="8"></textarea>${back()}`}
function exportData(){document.getElementById('backup').value=JSON.stringify({version:'mira-upgraded',data:Object.fromEntries(Object.entries(keys).map(([n,k])=>[n,arr(k)]))},null,2)}
function cmd(){let c=v('cmd').toLowerCase();if(c.includes('brain')||c.includes('help'))brain();else if(c.includes('letter'))letterMode();else if(c.includes('doctor'))doctorMode();else if(c.includes('reception'))reception();else if(c.includes('wait'))waiting();else if(c.includes('task'))tasks();else if(c.includes('reply')||c.includes('email'))communication();else if(c.includes('appointment')||c.includes('prepare'))appointment();else if(c.includes('document'))docs();else if(c.includes('search')||c.includes('find'))searchAll();else if(c.includes('guardian')||c.includes('barrier'))guardian();else if(c.includes('emergency'))emergency();else set('cmdOut','Try: brain, appointment, doctor, reception, letter, reply, waiting, task, document, search, guardian, emergency.')}
home();