const app=document.getElementById('app');
const base='Use clear UK English. Prefer written contact. Do not suggest phone calls unless unavoidable. Ask for written confirmation, named responsibility and clear next steps.';
const keys={ap:'mn_appt',org:'mn_org',wait:'mn_wait',task:'mn_task',doc:'mn_doc',line:'mn_line',mem:'mn_mem'};
let name=localStorage.mn_name||'Menglu';
function arr(k){try{return JSON.parse(localStorage[k]||'[]')}catch(e){return[]}}
function saveArr(k,a){localStorage[k]=JSON.stringify(a)}
function add(k,o){let a=arr(k);o.date=new Date().toLocaleString('en-GB');a.push(o);saveArr(k,a);alert('Saved')}
function v(id){return document.getElementById(id)?.value.trim()||''}
function set(id,t){let e=document.getElementById(id);if(e)e.textContent=t}
function say(t,l='en-GB'){let u=new SpeechSynthesisUtterance(t);u.lang=l;u.rate=.9;speechSynthesis.cancel();speechSynthesis.speak(u)}
function copy(id){navigator.clipboard.writeText(document.getElementById(id).textContent)}
function btn(t,fn,c=''){return `<button class="${c}" onclick="${fn}">${t}</button>`}
function back(){return btn('⬅ Back','home()')}
function home(){app.innerHTML=`<div class="card soft"><b>Reduce My Load</b><p class="small">Checks local records and shows what needs attention.</p>${btn('Run check','reduceLoad()','primary')}<div id="load" class="out small"></div></div><div class="card"><b>Command bar</b><input id="cmd" placeholder="prepare, reply, waiting, document, search, emergency">${btn('Run','cmd()','primary')}<div id="cmdOut" class="small out"></div></div><div id="today" class="card small"></div>`+
btn('🏠 Dashboard','dashboard()')+btn('⚡ Quick Actions','quick()')+btn('🗣 AAC','aac()')+btn('📅 Appointment','appointment()')+btn('🏁 End Appointment','endAppt()')+btn('📝 After Appointment','afterAppt()')+btn('👥 Organisations','orgs()')+btn('⏳ Waiting','waiting()')+btn('✅ Tasks','tasks()')+btn('📄 Documents','docs()')+btn('✉️ Communication','communication()')+btn('🔎 Universal Search','searchAll()')+btn('🛡 Guardian','guardian()')+btn('⚖️ Decision','decision()')+btn('🧪 Simulation','simulation()')+btn('🧠 AI Team','aiTeam()')+btn('📝 Timeline','timeline()')+btn('💾 Backup','backup()')+btn('🆘 Emergency','emergency()','danger')+btn('⚙ Settings','settings()');refresh()}
function refresh(){let el=document.getElementById('today');if(el)el.textContent=`Waiting: ${arr(keys.wait).length} | Tasks: ${arr(keys.task).length} | Documents: ${arr(keys.doc).length} | Timeline: ${arr(keys.line).length}`}
function dashboard(){app.innerHTML=`<h2>Dashboard</h2><div class="card out">Appointments: ${arr(keys.ap).length}\nOrganisations: ${arr(keys.org).length}\nWaiting items: ${arr(keys.wait).length}\nTasks: ${arr(keys.task).length}\nDocuments: ${arr(keys.doc).length}\nTimeline entries: ${arr(keys.line).length}\nMemory notes: ${arr(keys.mem).length}\n\nSuggested order:\n1. Urgent tasks\n2. Waiting items\n3. Appointments\n4. New documents\n5. Timeline update</div>${back()}`}
function quick(){app.innerHTML=`<h2>Quick Actions</h2>${btn('Prepare appointment','appointment()')}${btn('Draft reply','communication()')}${btn('Check waiting','waiting()')}${btn('Summarise document','docs()')}${btn('Check barrier','guardian()')}${btn('Record timeline','timeline()')}${back()}`}
function aac(){app.innerHTML=`<h2>AAC</h2>${btn('▶️ Short introduction',"say('Hello. My name is '+name+'. I may need support with communication.')")}${btn('▶️ Processing time',"say('Please give me extra time. Please ask one question at a time.')")}${btn('▶️ Written information',"say('Written information is easier for me. Please write down important information and next steps.')")}${btn('▶️ I cannot speak',"say('I cannot speak right now. Please give me time and use written communication.')")}${btn('▶️ No phone calls',"say('Please use email or written communication where possible.')")}${btn('▶️ 中文：说话困难',"say('我现在说话和组织语言比较困难。请慢一点，一次说一件事。','zh-CN')")}${btn('▶️ 中文：需要休息',"say('我需要安静休息。请不要连续追问。','zh-CN')")}${back()}`}
function appointment(){app.innerHTML=`<h2>Appointment</h2><select id="type"><option>Healthcare</option><option>Benefits / welfare</option><option>Social care</option><option>Housing</option><option>Banking</option><option>Government</option><option>Education</option><option>Other</option></select><input id="who" placeholder="Person or service"><input id="time" placeholder="Time"><input id="loc" placeholder="Location"><textarea id="why" rows="4" placeholder="Reason or notes"></textarea><div class="row">${btn('Generate','makeAppt()')}${btn('Save','saveAppt()')}</div><div id="out" class="card out"></div>${btn('▶️ Speak','say(document.getElementById(\'out\').textContent)')}${btn('📋 Copy','copy(\'out\')')}${back()}`}
function makeAppt(){let type=v('type'),s=`Hello. My name is ${name}.\n\nI have an appointment${v('who')?' with '+v('who'):''}${v('time')?' at '+v('time'):''}${v('loc')?' at '+v('loc'):''}.\n\nI may need support with communication. Please speak slowly, ask one question at a time, and provide written information where possible.\n\n`;if(v('why'))s+=`Reason / notes:\n${v('why')}\n\n`;if(type.includes('Housing'))s+='Please confirm the issue, responsibility, timescale and written update route.';else if(type.includes('Banking'))s+='Please confirm account protection, complaint, refund or next step in writing.';else if(type.includes('Benefits'))s+='Please confirm what evidence is needed, who is responsible and the timescale in writing.';else s+='Please provide a short written summary and next steps before I leave.';set('out',s)}
function saveAppt(){add(keys.ap,{type:v('type'),who:v('who'),time:v('time'),loc:v('loc'),why:v('why')})}
function endAppt(){app.innerHTML=`<h2>End Appointment</h2>${btn('▶️ Plain summary',"say('Before I leave, could you please summarise what we discussed today in plain language?')")}${btn('▶️ Easy Read',"say('Could you please provide Easy Read information or a short written summary where possible?')")}${btn('▶️ Next steps',"say('Could you please write down the next steps, who is responsible, and when I should expect to hear back?')")}${btn('▶️ Anything else needed',"say('Could you please confirm if anything needs to be sent, signed, booked, chased, or reviewed?')")}${btn('After appointment summary','afterAppt()')}${back()}`}
function afterAppt(){promptScreen('After Appointment','notes','Summarise these notes. Keep only new information. Create: new information, actions agreed, responsible person, deadlines, follow-up reminders, and timeline entry.')}
function form(title,k,a,b){app.innerHTML=`<h2>${title}</h2><input id="a" placeholder="${a}"><textarea id="b" rows="4" placeholder="${b}"></textarea>${btn('Save',`add('${k}',{a:v('a'),b:v('b')});list('${k}')`)}${btn('Show saved',`list('${k}')`)}<div id="list" class="card out"></div>${back()}`;list(k)}
function orgs(){form('Organisations',keys.org,'Organisation','Category, contact rules, notes')}
function waiting(){app.innerHTML=`<h2>Waiting</h2><input id="a" placeholder="Waiting for"><textarea id="b" rows="4" placeholder="Who, since date, due date, notes"></textarea>${btn('Save waiting item',`add('${keys.wait}',{a:v('a'),b:v('b')});list('${keys.wait}')`)}${btn('Follow-up prompt','followPrompt()')}<div id="list" class="card out"></div>${back()}`;list(keys.wait)}
function tasks(){form('Tasks',keys.task,'Task','Priority, due date, organisation')}
function docs(){app.innerHTML=`<h2>Documents</h2><input id="a" placeholder="Title or source"><textarea id="b" rows="6" placeholder="Paste document text or notes"></textarea>${btn('Save document note',`add('${keys.doc}',{a:v('a'),b:v('b')});list('${keys.doc}')`)}${btn('Document prompt','docPrompt()')}<div id="list" class="card out"></div>${back()}`;list(keys.doc)}
function communication(){promptScreen('Communication','comm','Draft a clear UK English message. Include accessibility needs only when relevant. Do not suggest phone calls. Ask for written confirmation and next steps where useful.')}
function guardian(){promptScreen('Accessibility Guardian','guard','Check this for deadlines, requests to phone, unclear responsibility, missing written confirmation, ignored communication needs, risks, and suggested wording.')}
function decision(){promptScreen('Decision Helper','dec','Help me compare options without making the decision for me. Include risks, accessibility impact, energy cost, missing information and safest next step.')}
function simulation(){promptScreen('Simulation Mode','sim','Prepare me for this situation. Predict likely questions, missing information, useful evidence, accessibility risks and safe responses.')}
function aiTeam(){promptScreen('Ask AI Team','team','Prepare this for another AI. Share only necessary context. Ask for second opinion, risks, missing information and practical next steps.')}
function promptScreen(title,id,lead){app.innerHTML=`<h2>${title}</h2><textarea id="${id}" rows="7" placeholder="Paste or type here"></textarea>${btn('Generate prompt',`set('pout','${lead}\\n\\n${base}\\n\\nInput:\\n'+v('${id}'))`)}<div id="pout" class="card out"></div>${btn('📋 Copy','copy(\'pout\')')}${back()}`}
function timeline(){app.innerHTML=`<h2>Timeline</h2>${btn('➕ Appointment or outing',"quick('Appointment or outing')")}${btn('➕ Crash or recovery',"quick('Crash or recovery')")}${btn('➕ Communication difficulty',"quick('Communication difficulty')")}${btn('➕ Support needed',"quick('Support needed')")}${btn('Show saved timeline',`list('${keys.line}')`)}<div id="list" class="card out"></div>${back()}`;list(keys.line)}
function memory(){form('Memory',keys.mem,'Memory title','Non-sensitive note')}
function searchAll(){app.innerHTML=`<h2>Universal Search</h2><input id="q" placeholder="Search local Mira data">${btn('Search','findLocal()')}<div id="res" class="card out"></div><textarea id="web" rows="4" placeholder="What current information needs checking?"></textarea>${btn('Generate web search prompt','webPrompt()')}<div id="webout" class="card out"></div>${back()}`}
function settings(){app.innerHTML=`<h2>Settings</h2><input id="nm" value="${name}">${btn('Save name',"localStorage.mn_name=v('nm');name=v('nm');alert('Saved')")}${back()}`}
function emergency(){app.innerHTML=`<h2>Emergency</h2>${btn('▶️ I cannot speak',"say('I cannot speak right now. Please give me time and use written communication.')",'danger')}${btn('▶️ I feel unwell',"say('I feel unwell and may need to sit or lie down safely.')")}${btn('▶️ Reduce overload',"say('Please reduce noise, lights, questions and pressure. I need a quiet place.')")}${back()}`}
function list(k){let a=arr(k);set('list',a.length?a.map((x,i)=>`${i+1}. ${x.date||''}\n${x.a||x.type||''}\n${x.b||x.why||''}`).join('\n\n'):'Nothing saved.')}
function quick(t){add(keys.line,{a:t,b:''});list(keys.line)}
function followPrompt(){set('list','Draft a short follow-up message for these waiting items. Ask for written confirmation, current status, named responsibility and expected timescale.\n\n'+base+'\n\n'+JSON.stringify(arr(keys.wait),null,2))}
function docPrompt(){set('list','Summarise this document. Extract sender, date, deadlines, actions needed, risks and filing category.\n\n'+base+'\n\n'+v('b'))}
function findLocal(){let q=v('q').toLowerCase(),hits=[];Object.values(keys).forEach(k=>arr(k).forEach((x,i)=>{let s=JSON.stringify(x);if(s.toLowerCase().includes(q))hits.push(`${k} #${i+1}: ${s}`)}));set('res',hits.length?hits.join('\n\n'):'No local matches.')}
function webPrompt(){set('webout','Search current reliable sources if this may have changed. Prefer official sources. Return key facts, source names, dates and action needed.\n\nQuestion:\n'+v('web'))}
function reduceLoad(){let urgent=arr(keys.task).filter(x=>JSON.stringify(x).toLowerCase().includes('urgent')).length;set('load',`Urgent tasks: ${urgent}\nWaiting items: ${arr(keys.wait).length}\nAppointments: ${arr(keys.ap).length}\nDocuments: ${arr(keys.doc).length}\nTimeline entries: ${arr(keys.line).length}\n\nSuggested order:\n1. Urgent tasks\n2. Waiting items\n3. Appointment preparation\n4. Document summary\n5. Timeline update`) }
function backup(){app.innerHTML=`<h2>Backup</h2>${btn('Export data','exportData()')}<textarea id="backup" rows="8"></textarea>${back()}`}
function exportData(){document.getElementById('backup').value=JSON.stringify({version:'next-beta',data:Object.fromEntries(Object.entries(keys).map(([n,k])=>[n,arr(k)]))},null,2)}
function cmd(){let c=v('cmd').toLowerCase();if(c.includes('wait'))waiting();else if(c.includes('task'))tasks();else if(c.includes('reply')||c.includes('email'))communication();else if(c.includes('appointment')||c.includes('prepare'))appointment();else if(c.includes('document')||c.includes('letter'))docs();else if(c.includes('search')||c.includes('find'))searchAll();else if(c.includes('guardian')||c.includes('barrier'))guardian();else if(c.includes('emergency'))emergency();else set('cmdOut','Try: appointment, reply, waiting, task, document, search, guardian, emergency.')} 
home();